In [1]:
!pip -q install -U cdsapi xarray netCDF4 pandas numpy scikit-learn

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 1.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 19.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 56.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 39.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 31.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 41.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 31.6 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.3, but you have pandas 3.0.5 which is incompatible.
numba 0.61.2 requires numpy<2.3,>=1.24, but you have numpy 2.5.2 which is incompatible.

In [5]:
import cdsapi
import getpass

API_KEY = getpass.getpass("Enter your ECMWF API key: ")

client = cdsapi.Client(
    url="https://cds.climate.copernicus.eu/api",
    key=API_KEY
)

print("✅ ECMWF client created successfully!")

Enter your ECMWF API key: ··········
✅ ECMWF client created successfully!

In [6]:
import os

print(os.listdir("/content"))

['.config', 'drive', 'sample_data']

In [7]:
from google.colab import files
uploaded = files.upload()

Saving skyguard_1m_synthetic_benchmark.csv to skyguard_1m_synthetic_benchmark.csv

In [8]:
import os

print(os.listdir("/content"))

['.config', 'drive', 'skyguard_1m_synthetic_benchmark.csv', 'sample_data']

In [9]:
import pandas as pd

skyguard_df = pd.read_csv(
    "/content/skyguard_1m_synthetic_benchmark.csv"
)

print("Dataset loaded successfully! ✅")
print("Shape:", skyguard_df.shape)

print("\nColumns:")
print(skyguard_df.columns.tolist())

print("\nFirst 5 rows:")
display(skyguard_df.head())

Dataset loaded successfully! ✅
Shape: (1000000, 12)

Columns:
['timestamp', 'station_id', 'station_name', 'latitude', 'longitude', 'temperature_C', 'pressure_hPa', 'relative_humidity_pct', 'anomaly', 'anomaly_type', 'severity', 'injected']

First 5 rows:

,timestamp,station_id,station_name,latitude,longitude,temperature_C,pressure_hPa,relative_humidity_pct,anomaly,anomaly_type,severity,injected
0,2024-01-01 00:00:00+00:00,ST002,Lucknow,26.85,80.95,15.69,1004.98,71.84,0,normal,normal,False
1,2024-01-01 01:00:00+00:00,ST016,Chandigarh,30.73,76.78,12.96,1001.45,82.85,0,normal,normal,False
2,2024-01-01 02:00:00+00:00,ST014,Guwahati,26.14,91.74,14.76,1003.39,74.04,0,normal,normal,False
3,2024-01-01 03:00:00+00:00,ST009,Patna,25.59,85.14,17.18,1007.02,74.06,0,normal,normal,False
4,2024-01-01 04:00:00+00:00,ST009,Patna,25.59,85.14,15.28,1005.95,70.46,0,normal,normal,False

In [10]:
print("========== DATASET INFORMATION ==========")

print("\nShape:")
print(skyguard_df.shape)

print("\nData types:")
print(skyguard_df.dtypes)

print("\nMissing values:")
print(skyguard_df.isna().sum())

========== DATASET INFORMATION ==========

Shape:
(1000000, 12)

Data types:
timestamp                    str
station_id                   str
station_name                 str
latitude                 float64
longitude                float64
temperature_C            float64
pressure_hPa             float64
relative_humidity_pct    float64
anomaly                    int64
anomaly_type                 str
severity                     str
injected                    bool
dtype: object

Missing values:
timestamp                   0
station_id                  0
station_name                0
latitude                    0
longitude                   0
temperature_C            2759
pressure_hPa             2652
relative_humidity_pct    2602
anomaly                     0
anomaly_type                0
severity                    0
injected                    0
dtype: int64

In [11]:
print("Columns:")
print(skyguard_df.columns.tolist())

Columns:
['timestamp', 'station_id', 'station_name', 'latitude', 'longitude', 'temperature_C', 'pressure_hPa', 'relative_humidity_pct', 'anomaly', 'anomaly_type', 'severity', 'injected']

In [12]:
print("Shape:", skyguard_df.shape)

print("\nFirst 5 rows:")
display(skyguard_df.head())

print("\nData types:")
print(skyguard_df.dtypes)

print("\nMissing values:")
print(skyguard_df.isna().sum())

Shape: (1000000, 12)

First 5 rows:

,timestamp,station_id,station_name,latitude,longitude,temperature_C,pressure_hPa,relative_humidity_pct,anomaly,anomaly_type,severity,injected
0,2024-01-01 00:00:00+00:00,ST002,Lucknow,26.85,80.95,15.69,1004.98,71.84,0,normal,normal,False
1,2024-01-01 01:00:00+00:00,ST016,Chandigarh,30.73,76.78,12.96,1001.45,82.85,0,normal,normal,False
2,2024-01-01 02:00:00+00:00,ST014,Guwahati,26.14,91.74,14.76,1003.39,74.04,0,normal,normal,False
3,2024-01-01 03:00:00+00:00,ST009,Patna,25.59,85.14,17.18,1007.02,74.06,0,normal,normal,False
4,2024-01-01 04:00:00+00:00,ST009,Patna,25.59,85.14,15.28,1005.95,70.46,0,normal,normal,False

Data types:
timestamp                    str
station_id                   str
station_name                 str
latitude                 float64
longitude                float64
temperature_C            float64
pressure_hPa             float64
relative_humidity_pct    float64
anomaly                    int64
anomaly_type                 str
severity                     str
injected                    bool
dtype: object

Missing values:
timestamp                   0
station_id                  0
station_name                0
latitude                    0
longitude                   0
temperature_C            2759
pressure_hPa             2652
relative_humidity_pct    2602
anomaly                     0
anomaly_type                0
severity                    0
injected                    0
dtype: int64

In [13]:
print("========== ANOMALY SUMMARY ==========")

print("\nAnomaly counts:")
print(skyguard_df["anomaly"].value_counts())

print("\nAnomaly types:")
print(skyguard_df["anomaly_type"].value_counts(dropna=False))

print("\nSeverity:")
print(skyguard_df["severity"].value_counts(dropna=False))

print("\nInjected:")
print(skyguard_df["injected"].value_counts(dropna=False))

========== ANOMALY SUMMARY ==========

Anomaly counts:
anomaly
0    920000
1     80000
Name: count, dtype: int64

Anomaly types:
anomaly_type
normal                        920000
multivariate_inconsistency      8207
humidity_spike                  8080
noise                           8045
offset                          8040
drift                           7994
temperature_spike               7980
pressure_spike                  7963
missing_value                   7952
frozen_sensor                   7939
duplicate/stale_reading         7800
Name: count, dtype: int64

Severity:
severity
normal    920000
medium     35809
low        28186
high       16005
Name: count, dtype: int64

Injected:
injected
False    920000
True      80000
Name: count, dtype: int64

In [14]:
skyguard_df["timestamp"] = pd.to_datetime(
    skyguard_df["timestamp"]
)

print("Start:", skyguard_df["timestamp"].min())
print("End:", skyguard_df["timestamp"].max())

print(
    "Number of stations:",
    skyguard_df["station_id"].nunique()
)

Start: 2024-01-01 00:00:00+00:00
End: 2029-09-14 07:00:00+00:00
Number of stations: 20

In [15]:
stations = (
    skyguard_df[
        ["station_id", "station_name", "latitude", "longitude"]
    ]
    .drop_duplicates()
    .sort_values("station_id")
)

display(stations)

   station_id station_name  latitude  longitude
55      ST001        Delhi     28.61      77.21
0       ST002      Lucknow     26.85      80.95
17      ST003       Mumbai     19.08      72.88
22      ST004      Kolkata     22.57      88.36
8       ST005      Chennai     13.08      80.27
38      ST006    Bengaluru     12.97      77.59
65      ST007    Hyderabad     17.39      78.49
21      ST008       Jaipur     26.91      75.79
3       ST009        Patna     25.59      85.14
19      ST010       Bhopal     23.26      77.41
10      ST011    Ahmedabad     23.02      72.57
33      ST012         Pune     18.52      73.86
25      ST013  Bhubaneswar     20.30      85.82
2       ST014     Guwahati     26.14      91.74
12      ST015     Srinagar     34.08      74.80
1       ST016   Chandigarh     30.73      76.78
18      ST017        Kochi      9.93      76.27
5       ST018       Nagpur     21.15      79.09
23      ST019       Ranchi     23.34      85.31
11      ST020     Dehradun     30.32      78.03

In [16]:
# Make sure timestamp is properly formatted
skyguard_df["timestamp"] = pd.to_datetime(
    skyguard_df["timestamp"],
    errors="coerce"
)

print("Start:", skyguard_df["timestamp"].min())
print("End:", skyguard_df["timestamp"].max())

print("\nNumber of rows:", len(skyguard_df))

print(
    "Number of stations:",
    skyguard_df["station_id"].nunique()
)

print("\nRows per station:")
print(
    skyguard_df["station_id"]
    .value_counts()
    .sort_index()
)

Start: 2024-01-01 00:00:00+00:00
End: 2029-09-14 07:00:00+00:00

Number of rows: 1000000
Number of stations: 20

Rows per station:
station_id
ST001    49802
ST002    50101
ST003    50251
ST004    50128
ST005    50044
ST006    49865
ST007    50051
ST008    49966
ST009    50147
ST010    49809
ST011    50180
ST012    50218
ST013    50215
ST014    49890
ST015    49948
ST016    49912
ST017    50015
ST018    49665
ST019    49795
ST020    49998
Name: count, dtype: int64

In [17]:
time_diff = (
    skyguard_df
    .sort_values(["station_id", "timestamp"])
    .groupby("station_id")["timestamp"]
    .diff()
)

print(time_diff.value_counts().head(10))

timestamp
0 days 01:00:00    411296
0 days 00:00:00    358715
0 days 02:00:00    147578
0 days 03:00:00     52616
0 days 04:00:00     19142
0 days 05:00:00      6822
0 days 06:00:00      2417
0 days 07:00:00       922
0 days 08:00:00       303
0 days 09:00:00       113
Name: count, dtype: int64

In [18]:
print("========== SKYGUARD DATASET ==========")

print("Rows:", len(skyguard_df))
print("Stations:", skyguard_df["station_id"].nunique())

print("\nStart:")
print(skyguard_df["timestamp"].min())

print("\nEnd:")
print(skyguard_df["timestamp"].max())

print("\nTime difference distribution:")
print(
    skyguard_df
    .sort_values(["station_id", "timestamp"])
    .groupby("station_id")["timestamp"]
    .diff()
    .value_counts()
    .head(15)
)

========== SKYGUARD DATASET ==========
Rows: 1000000
Stations: 20

Start:
2024-01-01 00:00:00+00:00

End:
2029-09-14 07:00:00+00:00

Time difference distribution:
timestamp
0 days 01:00:00    411296
0 days 00:00:00    358715
0 days 02:00:00    147578
0 days 03:00:00     52616
0 days 04:00:00     19142
0 days 05:00:00      6822
0 days 06:00:00      2417
0 days 07:00:00       922
0 days 08:00:00       303
0 days 09:00:00       113
0 days 10:00:00        36
0 days 11:00:00        15
0 days 12:00:00         4
0 days 13:00:00         1
Name: count, dtype: int64

In [19]:
import pandas as pd

skyguard_df["timestamp"] = pd.to_datetime(
    skyguard_df["timestamp"],
    utc=True
)

ERA5_AVAILABLE_END = pd.Timestamp(
    "2026-06-25 23:00:00",
    tz="UTC"
)

overlap_df = skyguard_df[
    skyguard_df["timestamp"] <= ERA5_AVAILABLE_END
].copy()

print("SkyGuard total rows:", len(skyguard_df))
print("Rows available for ERA5 hybrid:", len(overlap_df))

print("\nHybrid period:")
print(overlap_df["timestamp"].min())
print(overlap_df["timestamp"].max())

SkyGuard total rows: 1000000
Rows available for ERA5 hybrid: 435360

Hybrid period:
2024-01-01 00:00:00+00:00
2026-06-25 23:00:00+00:00

In [20]:
print("\nGeographical bounds:")

print("Minimum latitude :", skyguard_df["latitude"].min())
print("Maximum latitude :", skyguard_df["latitude"].max())
print("Minimum longitude:", skyguard_df["longitude"].min())
print("Maximum longitude:", skyguard_df["longitude"].max())

Geographical bounds:
Minimum latitude : 9.93
Maximum latitude : 34.08
Minimum longitude: 72.57
Maximum longitude: 91.74

In [21]:
ERA5_END = pd.Timestamp(
    "2026-06-25 23:00:00",
    tz="UTC"
)

overlap_df = skyguard_df[
    skyguard_df["timestamp"] <= ERA5_END
].copy()

print("Total SkyGuard rows:", len(skyguard_df))
print("Rows in ERA5 overlap:", len(overlap_df))

print("\nOverlap period:")
print(overlap_df["timestamp"].min())
print(overlap_df["timestamp"].max())

Total SkyGuard rows: 1000000
Rows in ERA5 overlap: 435360

Overlap period:
2024-01-01 00:00:00+00:00
2026-06-25 23:00:00+00:00

In [22]:
print("Latitude:")
print(
    skyguard_df["latitude"].min(),
    "to",
    skyguard_df["latitude"].max()
)

print("\nLongitude:")
print(
    skyguard_df["longitude"].min(),
    "to",
    skyguard_df["longitude"].max()
)

Latitude:
9.93 to 34.08

Longitude:
72.57 to 91.74

In [23]:
import numpy as np

stations = (
    skyguard_df[
        ["station_id", "station_name", "latitude", "longitude"]
    ]
    .drop_duplicates()
    .sort_values("station_id")
    .copy()
)

# ERA5 atmospheric grid = 0.25°
stations["era5_latitude"] = (
    np.round(stations["latitude"] * 4) / 4
)

stations["era5_longitude"] = (
    np.round(stations["longitude"] * 4) / 4
)

display(stations)

   station_id station_name  latitude  longitude  era5_latitude  era5_longitude
55      ST001        Delhi     28.61      77.21          28.50           77.25
0       ST002      Lucknow     26.85      80.95          26.75           81.00
17      ST003       Mumbai     19.08      72.88          19.00           73.00
22      ST004      Kolkata     22.57      88.36          22.50           88.25
8       ST005      Chennai     13.08      80.27          13.00           80.25
38      ST006    Bengaluru     12.97      77.59          13.00           77.50
65      ST007    Hyderabad     17.39      78.49          17.50           78.50
21      ST008       Jaipur     26.91      75.79          27.00           75.75
3       ST009        Patna     25.59      85.14          25.50           85.25
19      ST010       Bhopal     23.26      77.41          23.25           77.50
10      ST011    Ahmedabad     23.02      72.57          23.00           72.50
33      ST012         Pune     18.52      73.86          18.50           73.75
25      ST013  Bhubaneswar     20.30      85.82          20.25           85.75
2       ST014     Guwahati     26.14      91.74          26.25           91.75
12      ST015     Srinagar     34.08      74.80          34.00           74.75
1       ST016   Chandigarh     30.73      76.78          30.75           76.75
18      ST017        Kochi      9.93      76.27          10.00           76.25
5       ST018       Nagpur     21.15      79.09          21.25           79.00
23      ST019       Ranchi     23.34      85.31          23.25           85.25
11      ST020     Dehradun     30.32      78.03          30.25           78.00

In [24]:
print("Number of stations:", len(stations))

print("\nUnique ERA5 grid points:",
      stations[
          ["era5_latitude", "era5_longitude"]
      ].drop_duplicates().shape[0])

Number of stations: 20

Unique ERA5 grid points: 20

In [25]:
import numpy as np

stations = (
    skyguard_df[
        ["station_id", "station_name", "latitude", "longitude"]
    ]
    .drop_duplicates()
    .sort_values("station_id")
    .copy()
)

stations["era5_latitude"] = (
    np.round(stations["latitude"] * 4) / 4
)

stations["era5_longitude"] = (
    np.round(stations["longitude"] * 4) / 4
)

display(stations)

   station_id station_name  latitude  longitude  era5_latitude  era5_longitude
55      ST001        Delhi     28.61      77.21          28.50           77.25
0       ST002      Lucknow     26.85      80.95          26.75           81.00
17      ST003       Mumbai     19.08      72.88          19.00           73.00
22      ST004      Kolkata     22.57      88.36          22.50           88.25
8       ST005      Chennai     13.08      80.27          13.00           80.25
38      ST006    Bengaluru     12.97      77.59          13.00           77.50
65      ST007    Hyderabad     17.39      78.49          17.50           78.50
21      ST008       Jaipur     26.91      75.79          27.00           75.75
3       ST009        Patna     25.59      85.14          25.50           85.25
19      ST010       Bhopal     23.26      77.41          23.25           77.50
10      ST011    Ahmedabad     23.02      72.57          23.00           72.50
33      ST012         Pune     18.52      73.86          18.50           73.75
25      ST013  Bhubaneswar     20.30      85.82          20.25           85.75
2       ST014     Guwahati     26.14      91.74          26.25           91.75
12      ST015     Srinagar     34.08      74.80          34.00           74.75
1       ST016   Chandigarh     30.73      76.78          30.75           76.75
18      ST017        Kochi      9.93      76.27          10.00           76.25
5       ST018       Nagpur     21.15      79.09          21.25           79.00
23      ST019       Ranchi     23.34      85.31          23.25           85.25
11      ST020     Dehradun     30.32      78.03          30.25           78.00

In [26]:
print("ECMWF client:", "✅ Ready" if "client" in globals() else "❌ Missing")

ECMWF client: ✅ Ready

In [27]:
# ERA5 overlap period
start_date = "2024-01-01"
end_date = "2026-06-25"

years = list(range(2024, 2027))

months_by_year = {
    2024: [f"{m:02d}" for m in range(1, 13)],
    2025: [f"{m:02d}" for m in range(1, 13)],
    2026: [f"{m:02d}" for m in range(1, 7)]
}

print("ERA5 collection period:")
print(start_date, "→", end_date)

print("\nYears:", years)
print("2024 months:", months_by_year[2024])
print("2025 months:", months_by_year[2025])
print("2026 months:", months_by_year[2026])

ERA5 collection period:
2024-01-01 → 2026-06-25

Years: [2024, 2025, 2026]
2024 months: ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12']
2025 months: ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12']
2026 months: ['01', '02', '03', '04', '05', '06']

In [28]:
import os

ERA5_DIR = "/content/era5_data"

os.makedirs(ERA5_DIR, exist_ok=True)

print("✅ ERA5 storage folder ready:")
print(ERA5_DIR)

✅ ERA5 storage folder ready:
/content/era5_data

In [29]:
era5_points = (
    stations[
        ["era5_latitude", "era5_longitude"]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

print("Unique ERA5 grid points:", len(era5_points))

display(era5_points)

Unique ERA5 grid points: 20

    era5_latitude  era5_longitude
0           28.50           77.25
1           26.75           81.00
2           19.00           73.00
3           22.50           88.25
4           13.00           80.25
5           13.00           77.50
6           17.50           78.50
7           27.00           75.75
8           25.50           85.25
9           23.25           77.50
10          23.00           72.50
11          18.50           73.75
12          20.25           85.75
13          26.25           91.75
14          34.00           74.75
15          30.75           76.75
16          10.00           76.25
17          21.25           79.00
18          23.25           85.25
19          30.25           78.00

In [30]:
request = {
    "product_type": "reanalysis",

    "variable": [
        "2m_temperature",
        "2m_dewpoint_temperature",
        "surface_pressure"
    ],

    "year": "2024",
    "month": "01",

    "day": [
        f"{d:02d}" for d in range(1, 32)
    ],

    "time": [
        f"{h:02d}:00" for h in range(24)
    ],

    "area": [
        float(era5_points["era5_latitude"].max()),
        float(era5_points["era5_longitude"].min()),
        float(era5_points["era5_latitude"].min()),
        float(era5_points["era5_longitude"].max())
    ],

    "data_format": "netcdf",
    "download_format": "unarchived"
}

print("Request area:")
print(request["area"])

print("\nDownloading January 2024...")

Request area:
[34.0, 72.5, 10.0, 91.75]

Downloading January 2024...

In [31]:
client.retrieve(
    "reanalysis-era5-single-levels",
    request,
    f"{ERA5_DIR}/era5_2024_01.nc"
)

print("✅ January 2024 downloaded successfully!")

2026-08-23 17:32:30,881 INFO Request ID is 309cf920-77d2-4062-980b-4bf8d19d3398
INFO:ecmwf.datastores.legacy_client:Request ID is 309cf920-77d2-4062-980b-4bf8d19d3398
2026-08-23 17:32:31,062 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-23 17:32:39,804 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-23 17:32:45,137 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

4f1aaa2236f13ce2dcd7cd5aeed62329.nc:   0%|          | 0.00/25.6M [00:00<?, ?B/s]

✅ January 2024 downloaded successfully!

In [32]:
import xarray as xr
import os

file_path = "/content/era5_data/era5_2024_01.nc"

print("File exists:", os.path.exists(file_path))
print("File size:", round(os.path.getsize(file_path) / (1024**2), 2), "MB")

era5_jan = xr.open_dataset(file_path)

print("\nDataset:")
print(era5_jan)

print("\nVariables:")
print(list(era5_jan.data_vars))

print("\nDimensions:")
print(era5_jan.dims)

File exists: True
File size: 25.62 MB

Dataset:
<xarray.Dataset> Size: 68MB
Dimensions:     (valid_time: 744, latitude: 97, longitude: 78)
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 6kB 2024-01-01 ... 2024-01-31T23:...
    expver      (valid_time) <U4 12kB ...
  * latitude    (latitude) float64 776B 34.0 33.75 33.5 ... 10.5 10.25 10.0
  * longitude   (longitude) float64 624B 72.5 72.75 73.0 ... 91.25 91.5 91.75
    number      int64 8B ...
Data variables:
    t2m         (valid_time, latitude, longitude) float32 23MB ...
    d2m         (valid_time, latitude, longitude) float32 23MB ...
    sp          (valid_time, latitude, longitude) float32 23MB ...
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-08-23T13:44 GRIB to CDM+CF via cfgrib-0.9.1...

Variables:
['t2m', 'd2m', 'sp']

Dimensions:
FrozenMappingWarningOnValuesAccess({'valid_time': 744, 'latitude': 97, 'longitude': 78})

In [33]:
print("\nCoordinates:")
print(era5_jan.coords)

print("\nTemperature range:")
print(
    float(era5_jan["t2m"].min()),
    "to",
    float(era5_jan["t2m"].max()),
    "K"
)

print("\nPressure range:")
print(
    float(era5_jan["sp"].min()),
    "to",
    float(era5_jan["sp"].max()),
    "Pa"
)

Coordinates:
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 6kB 2024-01-01 ... 2024-01-31T23:...
    expver      (valid_time) <U4 12kB ...
  * latitude    (latitude) float64 776B 34.0 33.75 33.5 ... 10.5 10.25 10.0
  * longitude   (longitude) float64 624B 72.5 72.75 73.0 ... 91.25 91.5 91.75
    number      int64 8B ...

Temperature range:
232.4225311279297 to 310.297119140625 K

Pressure range:
49976.86328125 to 102380.328125 Pa

In [34]:
import os
import calendar
import time

ERA5_DIR = "/content/era5_data"
os.makedirs(ERA5_DIR, exist_ok=True)

# Make sure the ECMWF client exists
if "client" not in globals():
    raise RuntimeError(
        "ECMWF client is not available. "
        "Please recreate the client before running this cell."
    )

# ERA5 collection period
start_year = 2024
end_year = 2026

# 2026 is available only through June for our project
last_month = {
    2024: 12,
    2025: 12,
    2026: 6
}

variables = [
    "2m_temperature",
    "2m_dewpoint_temperature",
    "surface_pressure"
]

# Bounding box covering all 20 stations
north = float(stations["era5_latitude"].max())
west = float(stations["era5_longitude"].min())
south = float(stations["era5_latitude"].min())
east = float(stations["era5_longitude"].max())

area = [north, west, south, east]

print("ERA5 area:", area)
print("Variables:", variables)
print()

for year in range(start_year, end_year + 1):

    for month in range(1, last_month[year] + 1):

        output_file = (
            f"{ERA5_DIR}/era5_{year}_{month:02d}.nc"
        )

        # Skip files that have already been downloaded
        if os.path.exists(output_file):
            print(
                f"⏭️ Skipping {year}-{month:02d} "
                f"(already exists)"
            )
            continue

        num_days = calendar.monthrange(year, month)[1]

        request = {
            "product_type": "reanalysis",

            "variable": variables,

            "year": str(year),

            "month": f"{month:02d}",

            "day": [
                f"{day:02d}"
                for day in range(1, num_days + 1)
            ],

            "time": [
                f"{hour:02d}:00"
                for hour in range(24)
            ],

            "area": area,

            "data_format": "netcdf",

            "download_format": "unarchived"
        }

        print(
            f"\n⬇️ Downloading ERA5 "
            f"{year}-{month:02d}..."
        )

        try:

            client.retrieve(
                "reanalysis-era5-single-levels",
                request,
                output_file
            )

            print(
                f"✅ Successfully downloaded "
                f"{year}-{month:02d}"
            )

        except Exception as e:

            print(
                f"❌ Failed {year}-{month:02d}"
            )

            print("Error:", e)

            print(
                "\nThe loop will continue with "
                "the next month."
            )

        # Small pause between requests
        time.sleep(2)

print("\n🎉 ERA5 collection loop finished!")

ERA5 area: [34.0, 72.5, 10.0, 91.75]
Variables: ['2m_temperature', '2m_dewpoint_temperature', 'surface_pressure']

⏭️ Skipping 2024-01 (already exists)

⬇️ Downloading ERA5 2024-02...

2026-08-23 17:33:09,376 INFO Request ID is 916d4eb2-bddf-459d-9a37-45c9e225d770
INFO:ecmwf.datastores.legacy_client:Request ID is 916d4eb2-bddf-459d-9a37-45c9e225d770
2026-08-23 17:33:09,521 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-23 17:33:23,680 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-23 17:33:31,486 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

b1ae1f2738081450325d505e23345af0.nc:   0%|          | 0.00/24.0M [00:00<?, ?B/s]

✅ Successfully downloaded 2024-02

⬇️ Downloading ERA5 2024-03...

2026-08-23 17:33:38,031 INFO Request ID is 935d17d5-1b7f-4915-b93a-a5aa083caa72
INFO:ecmwf.datastores.legacy_client:Request ID is 935d17d5-1b7f-4915-b93a-a5aa083caa72
2026-08-23 17:33:38,186 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-23 17:34:00,091 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

e3cb8a62e17db82947fce038459455a3.nc:   0%|          | 0.00/25.7M [00:00<?, ?B/s]

✅ Successfully downloaded 2024-03

⬇️ Downloading ERA5 2024-04...

WARNING:multiurl.retry:Recovering from HTTP error [502 Bad Gateway], attempt 1 of 500
WARNING:multiurl.retry:Retrying in 120 seconds
2026-08-23 17:36:06,666 INFO Request ID is 72c228ba-86b1-4560-ad9d-b86551b77d69
INFO:ecmwf.datastores.legacy_client:Request ID is 72c228ba-86b1-4560-ad9d-b86551b77d69
2026-08-23 17:36:06,825 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-23 17:36:23,817 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

37c4019822fa4fcbd817907f7df869d9.nc:   0%|          | 0.00/24.8M [00:00<?, ?B/s]

✅ Successfully downloaded 2024-04

⬇️ Downloading ERA5 2024-05...

2026-08-23 17:36:29,815 INFO Request ID is a7a96b54-813c-45ce-89e9-b53d436b2799
INFO:ecmwf.datastores.legacy_client:Request ID is a7a96b54-813c-45ce-89e9-b53d436b2799
2026-08-23 17:36:29,960 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-23 17:36:51,705 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

94b26ed6a5dcfcbdb264b99a0dc205b.nc:   0%|          | 0.00/25.6M [00:00<?, ?B/s]

✅ Successfully downloaded 2024-05

⬇️ Downloading ERA5 2024-06...

2026-08-23 17:36:57,397 INFO Request ID is d6d5210e-8a97-4b06-921a-5daadaca130f
INFO:ecmwf.datastores.legacy_client:Request ID is d6d5210e-8a97-4b06-921a-5daadaca130f
2026-08-23 17:36:57,540 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-23 17:37:11,785 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-23 17:37:19,537 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

a176eb28e6dc7c5feee38809bd64d7eb.nc:   0%|          | 0.00/24.4M [00:00<?, ?B/s]

✅ Successfully downloaded 2024-06

⬇️ Downloading ERA5 2024-07...

2026-08-23 17:37:25,264 INFO Request ID is 4d773aea-7b37-4613-878b-435b5613e319
INFO:ecmwf.datastores.legacy_client:Request ID is 4d773aea-7b37-4613-878b-435b5613e319
2026-08-23 17:37:25,422 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-23 17:37:39,388 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

9c22dea246cd1d656c0a8b5dd720735.nc:   0%|          | 0.00/24.8M [00:00<?, ?B/s]

✅ Successfully downloaded 2024-07

⬇️ Downloading ERA5 2024-08...

2026-08-23 17:37:45,039 INFO Request ID is a127491b-bd63-4be0-9dda-dfde5996a701
INFO:ecmwf.datastores.legacy_client:Request ID is a127491b-bd63-4be0-9dda-dfde5996a701
2026-08-23 17:37:45,196 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-23 17:37:54,919 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-23 17:38:00,132 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

e3079667709bc9b76093fb04d9380ef8.nc:   0%|          | 0.00/24.8M [00:00<?, ?B/s]

✅ Successfully downloaded 2024-08

⬇️ Downloading ERA5 2024-09...

2026-08-23 17:38:05,974 INFO Request ID is ddcf9f13-a141-4b34-9a79-b830465ea5ff
INFO:ecmwf.datastores.legacy_client:Request ID is ddcf9f13-a141-4b34-9a79-b830465ea5ff
2026-08-23 17:38:06,120 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-23 17:38:27,770 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

f247222b436203c6fc4eaebef22e5088.nc:   0%|          | 0.00/24.1M [00:00<?, ?B/s]

✅ Successfully downloaded 2024-09

⬇️ Downloading ERA5 2024-10...

2026-08-23 17:38:36,085 INFO Request ID is 69876775-979d-42ba-ae44-c62a866652b9
INFO:ecmwf.datastores.legacy_client:Request ID is 69876775-979d-42ba-ae44-c62a866652b9
2026-08-23 17:38:36,229 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-23 17:38:50,641 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

cd97f84e7cfe34c0e4d24a86ded2111a.nc:   0%|          | 0.00/25.3M [00:00<?, ?B/s]

✅ Successfully downloaded 2024-10

⬇️ Downloading ERA5 2024-11...

2026-08-23 17:38:56,715 INFO Request ID is 88e55248-5a52-42b6-bddb-5f8631976614
INFO:ecmwf.datastores.legacy_client:Request ID is 88e55248-5a52-42b6-bddb-5f8631976614
2026-08-23 17:38:56,859 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-23 17:39:19,006 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

ffc0ab7e4743a6ecbfa24a75e184f90a.nc:   0%|          | 0.00/24.7M [00:00<?, ?B/s]

✅ Successfully downloaded 2024-11

⬇️ Downloading ERA5 2024-12...

2026-08-23 17:39:24,783 INFO Request ID is f613cc98-4b71-489f-abb4-a123e8ec0b3e
INFO:ecmwf.datastores.legacy_client:Request ID is f613cc98-4b71-489f-abb4-a123e8ec0b3e
2026-08-23 17:39:24,937 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-23 17:39:46,980 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

ff952a8d2aa9b9bd1fffb517bbbf44e1.nc:   0%|          | 0.00/25.6M [00:00<?, ?B/s]

✅ Successfully downloaded 2024-12

⬇️ Downloading ERA5 2025-01...

2026-08-23 17:39:54,030 INFO Request ID is 7d5b7dc9-4f9f-4ace-91d3-4c236757522a
INFO:ecmwf.datastores.legacy_client:Request ID is 7d5b7dc9-4f9f-4ace-91d3-4c236757522a
2026-08-23 17:39:54,197 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-23 17:40:08,131 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-23 17:40:15,886 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

7a417d94a832a06d3b42ac5d0fa3d24b.nc:   0%|          | 0.00/25.7M [00:00<?, ?B/s]

✅ Successfully downloaded 2025-01

⬇️ Downloading ERA5 2025-02...

2026-08-23 17:40:22,327 INFO Request ID is 5593b575-5455-47b3-8e69-b949bc2f658b
INFO:ecmwf.datastores.legacy_client:Request ID is 5593b575-5455-47b3-8e69-b949bc2f658b
2026-08-23 17:40:22,471 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-23 17:40:37,195 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

316725bcaf6e948dd34170e5c2b1473.nc:   0%|          | 0.00/23.2M [00:00<?, ?B/s]

✅ Successfully downloaded 2025-02

⬇️ Downloading ERA5 2025-03...

2026-08-23 17:40:43,588 INFO Request ID is d2ef64fa-4c67-486b-b8ae-cf47d5dd38d4
INFO:ecmwf.datastores.legacy_client:Request ID is d2ef64fa-4c67-486b-b8ae-cf47d5dd38d4
2026-08-23 17:40:43,743 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-23 17:41:05,644 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

fc1a9cde474e43a54fa69ede0c0ac75.nc:   0%|          | 0.00/25.7M [00:00<?, ?B/s]

✅ Successfully downloaded 2025-03

⬇️ Downloading ERA5 2025-04...

2026-08-23 17:41:11,559 INFO Request ID is 7edd9afc-9a21-45b0-bb84-c2a71b6ca21e
INFO:ecmwf.datastores.legacy_client:Request ID is 7edd9afc-9a21-45b0-bb84-c2a71b6ca21e
2026-08-23 17:41:11,701 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-23 17:41:25,662 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-23 17:41:35,616 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

fdfeff15021a82219ef1af0870257f8c.nc:   0%|          | 0.00/24.9M [00:00<?, ?B/s]

✅ Successfully downloaded 2025-04

⬇️ Downloading ERA5 2025-05...

2026-08-23 17:41:41,493 INFO Request ID is a2120dd0-8d1d-4e2e-9c2e-bf6768b8e1da
INFO:ecmwf.datastores.legacy_client:Request ID is a2120dd0-8d1d-4e2e-9c2e-bf6768b8e1da
2026-08-23 17:41:43,793 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-23 17:42:05,489 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

5be86dd5dabcd7475b409e4695410647.nc:   0%|          | 0.00/25.3M [00:00<?, ?B/s]

✅ Successfully downloaded 2025-05

⬇️ Downloading ERA5 2025-06...

2026-08-23 17:42:12,704 INFO Request ID is 17cd8bf4-02f9-4ee1-ba46-e4b962cb24da
INFO:ecmwf.datastores.legacy_client:Request ID is 17cd8bf4-02f9-4ee1-ba46-e4b962cb24da
2026-08-23 17:42:12,848 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-23 17:42:46,054 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

8a79e120c60c9023ce22b11205a65d84.nc:   0%|          | 0.00/24.3M [00:00<?, ?B/s]

✅ Successfully downloaded 2025-06

⬇️ Downloading ERA5 2025-07...

2026-08-23 17:42:52,690 INFO Request ID is 639fab46-e9d6-4da4-af34-73debb261cb7
INFO:ecmwf.datastores.legacy_client:Request ID is 639fab46-e9d6-4da4-af34-73debb261cb7
2026-08-23 17:42:52,830 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-23 17:43:06,842 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-23 17:43:14,581 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

79048af03a74fc5d001af2ada291aa0e.nc:   0%|          | 0.00/24.8M [00:00<?, ?B/s]

✅ Successfully downloaded 2025-07

⬇️ Downloading ERA5 2025-08...

2026-08-23 17:43:21,241 INFO Request ID is d78ca3f5-38a8-4ddd-bcfb-e610e750419e
INFO:ecmwf.datastores.legacy_client:Request ID is d78ca3f5-38a8-4ddd-bcfb-e610e750419e
2026-08-23 17:43:21,391 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-23 17:43:37,647 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

717c0dd216d75a642443b5c0fb7c1ac3.nc:   0%|          | 0.00/24.8M [00:00<?, ?B/s]

✅ Successfully downloaded 2025-08

⬇️ Downloading ERA5 2025-09...

2026-08-23 17:43:43,534 INFO Request ID is aca77880-4056-40a6-b987-6790854f3cb9
INFO:ecmwf.datastores.legacy_client:Request ID is aca77880-4056-40a6-b987-6790854f3cb9
2026-08-23 17:43:43,687 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-23 17:43:59,061 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-23 17:44:06,832 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

a0d892d69a5245e812fd1303a64505c9.nc:   0%|          | 0.00/24.1M [00:00<?, ?B/s]

✅ Successfully downloaded 2025-09

⬇️ Downloading ERA5 2025-10...

2026-08-23 17:44:13,270 INFO Request ID is fc61d596-12a7-4a9a-b705-e18ef765a46f
INFO:ecmwf.datastores.legacy_client:Request ID is fc61d596-12a7-4a9a-b705-e18ef765a46f
2026-08-23 17:44:13,421 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-23 17:44:28,114 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

2950703ba9a7360c500e37f09a8630f5.nc:   0%|          | 0.00/25.3M [00:00<?, ?B/s]

✅ Successfully downloaded 2025-10

⬇️ Downloading ERA5 2025-11...

2026-08-23 17:44:34,277 INFO Request ID is f5eaec06-a501-434b-b8a0-be07c1db87ac
INFO:ecmwf.datastores.legacy_client:Request ID is f5eaec06-a501-434b-b8a0-be07c1db87ac
2026-08-23 17:44:34,428 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-23 17:44:44,731 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-23 17:44:49,957 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

730015255f33cd34eed2a7526b1fcc16.nc:   0%|          | 0.00/24.9M [00:00<?, ?B/s]

✅ Successfully downloaded 2025-11

⬇️ Downloading ERA5 2025-12...

2026-08-23 17:44:55,579 INFO Request ID is 17989662-5ef0-412c-9ece-755645f2385a
INFO:ecmwf.datastores.legacy_client:Request ID is 17989662-5ef0-412c-9ece-755645f2385a
2026-08-23 17:44:55,739 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-23 17:45:18,614 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

e260b7f78ba45fa156e2aca6c05717f0.nc:   0%|          | 0.00/25.7M [00:00<?, ?B/s]

✅ Successfully downloaded 2025-12

⬇️ Downloading ERA5 2026-01...

2026-08-23 17:45:25,680 INFO Request ID is 1a6b2bd7-6c5e-48cd-bc9e-6dad9e4506bf
INFO:ecmwf.datastores.legacy_client:Request ID is 1a6b2bd7-6c5e-48cd-bc9e-6dad9e4506bf
2026-08-23 17:45:25,936 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-23 17:45:39,845 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-23 17:45:47,581 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

75a00db0a8626835eccc19d8e0deab75.nc:   0%|          | 0.00/25.7M [00:00<?, ?B/s]

✅ Successfully downloaded 2026-01

⬇️ Downloading ERA5 2026-02...

2026-08-23 17:46:57,486 INFO Request ID is 2f84861d-55fb-4cea-8981-893acfd7425b
INFO:ecmwf.datastores.legacy_client:Request ID is 2f84861d-55fb-4cea-8981-893acfd7425b
2026-08-23 17:46:57,652 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-23 17:47:11,588 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-23 17:47:19,530 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

bbdfcb8db34ead2bd7cfd962b5902b96.nc:   0%|          | 0.00/23.3M [00:00<?, ?B/s]

✅ Successfully downloaded 2026-02

⬇️ Downloading ERA5 2026-03...

2026-08-23 17:47:28,815 INFO Request ID is a7fded96-7aaf-4a96-8338-ad231ebba8d6
INFO:ecmwf.datastores.legacy_client:Request ID is a7fded96-7aaf-4a96-8338-ad231ebba8d6
2026-08-23 17:47:28,958 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-23 17:47:37,705 INFO status has been updated to running
INFO:ecmwf.datastores.legacy_client:status has been updated to running
2026-08-23 17:47:42,937 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

8135c28a524cfdedf5133be424061df4.nc:   0%|          | 0.00/25.6M [00:00<?, ?B/s]

✅ Successfully downloaded 2026-03

⬇️ Downloading ERA5 2026-04...

2026-08-23 17:48:13,571 INFO Request ID is f4f725f1-9a29-48fa-bed1-258799260e71
INFO:ecmwf.datastores.legacy_client:Request ID is f4f725f1-9a29-48fa-bed1-258799260e71
2026-08-23 17:48:13,726 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-23 17:48:27,632 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

f69101ebf45594c78b96e2ccdb605390.nc:   0%|          | 0.00/24.8M [00:00<?, ?B/s]

✅ Successfully downloaded 2026-04

⬇️ Downloading ERA5 2026-05...

2026-08-23 17:48:33,621 INFO Request ID is 28d7cae0-3f6c-4662-a7fb-61a8d8313142
INFO:ecmwf.datastores.legacy_client:Request ID is 28d7cae0-3f6c-4662-a7fb-61a8d8313142
2026-08-23 17:48:33,780 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-23 17:48:55,482 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

e2e814b3a5f5166ebed8cf5a0834dff9.nc:   0%|          | 0.00/25.5M [00:00<?, ?B/s]

✅ Successfully downloaded 2026-05

⬇️ Downloading ERA5 2026-06...

2026-08-23 17:49:01,376 INFO Request ID is c57baf1b-eaa2-40b6-b2c0-2d135aa09166
INFO:ecmwf.datastores.legacy_client:Request ID is c57baf1b-eaa2-40b6-b2c0-2d135aa09166
2026-08-23 17:49:01,537 INFO status has been updated to accepted
INFO:ecmwf.datastores.legacy_client:status has been updated to accepted
2026-08-23 17:49:26,135 INFO status has been updated to successful
INFO:ecmwf.datastores.legacy_client:status has been updated to successful

23a77f79153a4d2a7c8d7091c394df80.nc:   0%|          | 0.00/24.3M [00:00<?, ?B/s]

✅ Successfully downloaded 2026-06

🎉 ERA5 collection loop finished!

In [ ]:
#DATA ENGINEERING

In [35]:
import os

era5_files = sorted(
    f for f in os.listdir("/content/era5_data")
    if f.endswith(".nc")
)

print("Number of ERA5 files:", len(era5_files))

print("\nFiles:")
for f in era5_files:
    print(f)

Number of ERA5 files: 30

Files:
era5_2024_01.nc
era5_2024_02.nc
era5_2024_03.nc
era5_2024_04.nc
era5_2024_05.nc
era5_2024_06.nc
era5_2024_07.nc
era5_2024_08.nc
era5_2024_09.nc
era5_2024_10.nc
era5_2024_11.nc
era5_2024_12.nc
era5_2025_01.nc
era5_2025_02.nc
era5_2025_03.nc
era5_2025_04.nc
era5_2025_05.nc
era5_2025_06.nc
era5_2025_07.nc
era5_2025_08.nc
era5_2025_09.nc
era5_2025_10.nc
era5_2025_11.nc
era5_2025_12.nc
era5_2026_01.nc
era5_2026_02.nc
era5_2026_03.nc
era5_2026_04.nc
era5_2026_05.nc
era5_2026_06.nc

In [36]:
import xarray as xr

test_file = "/content/era5_data/era5_2024_02.nc"

ds = xr.open_dataset(test_file)

print(ds)
print("\nVariables:")
print(list(ds.data_vars))

<xarray.Dataset> Size: 63MB
Dimensions:     (valid_time: 696, latitude: 97, longitude: 78)
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 6kB 2024-02-01 ... 2024-02-29T23:...
    expver      (valid_time) <U4 11kB ...
  * latitude    (latitude) float64 776B 34.0 33.75 33.5 ... 10.5 10.25 10.0
  * longitude   (longitude) float64 624B 72.5 72.75 73.0 ... 91.25 91.5 91.75
    number      int64 8B ...
Data variables:
    t2m         (valid_time, latitude, longitude) float32 21MB ...
    d2m         (valid_time, latitude, longitude) float32 21MB ...
    sp          (valid_time, latitude, longitude) float32 21MB ...
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-08-23T13:48 GRIB to CDM+CF via cfgrib-0.9.1...

Variables:
['t2m', 'd2m', 'sp']

In [37]:
import os

era5_files = sorted(
    f for f in os.listdir("/content/era5_data")
    if f.endswith(".nc")
)

print("Number of ERA5 files:", len(era5_files))

for f in era5_files:
    print(f)

Number of ERA5 files: 30
era5_2024_01.nc
era5_2024_02.nc
era5_2024_03.nc
era5_2024_04.nc
era5_2024_05.nc
era5_2024_06.nc
era5_2024_07.nc
era5_2024_08.nc
era5_2024_09.nc
era5_2024_10.nc
era5_2024_11.nc
era5_2024_12.nc
era5_2025_01.nc
era5_2025_02.nc
era5_2025_03.nc
era5_2025_04.nc
era5_2025_05.nc
era5_2025_06.nc
era5_2025_07.nc
era5_2025_08.nc
era5_2025_09.nc
era5_2025_10.nc
era5_2025_11.nc
era5_2025_12.nc
era5_2026_01.nc
era5_2026_02.nc
era5_2026_03.nc
era5_2026_04.nc
era5_2026_05.nc
era5_2026_06.nc

In [38]:
import xarray as xr

test_file = "/content/era5_data/era5_2024_02.nc"

ds = xr.open_dataset(test_file)

print(ds)

print("\nVariables:")
print(list(ds.data_vars))

<xarray.Dataset> Size: 63MB
Dimensions:     (valid_time: 696, latitude: 97, longitude: 78)
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 6kB 2024-02-01 ... 2024-02-29T23:...
    expver      (valid_time) <U4 11kB ...
  * latitude    (latitude) float64 776B 34.0 33.75 33.5 ... 10.5 10.25 10.0
  * longitude   (longitude) float64 624B 72.5 72.75 73.0 ... 91.25 91.5 91.75
    number      int64 8B ...
Data variables:
    t2m         (valid_time, latitude, longitude) float32 21MB ...
    d2m         (valid_time, latitude, longitude) float32 21MB ...
    sp          (valid_time, latitude, longitude) float32 21MB ...
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-08-23T13:48 GRIB to CDM+CF via cfgrib-0.9.1...

Variables:
['t2m', 'd2m', 'sp']

In [39]:
import pandas as pd
import numpy as np

skyguard = pd.read_csv(
    "/content/skyguard_1m_synthetic_benchmark.csv"
)

print("Original shape:", skyguard.shape)
print("Columns:", skyguard.columns.tolist())

Original shape: (1000000, 12)
Columns: ['timestamp', 'station_id', 'station_name', 'latitude', 'longitude', 'temperature_C', 'pressure_hPa', 'relative_humidity_pct', 'anomaly', 'anomaly_type', 'severity', 'injected']

In [40]:
skyguard["timestamp"] = pd.to_datetime(
    skyguard["timestamp"],
    utc=True,
    errors="coerce"
)

print("Timestamp dtype:", skyguard["timestamp"].dtype)

print("Invalid timestamps:",
      skyguard["timestamp"].isna().sum())

print("Start:", skyguard["timestamp"].min())
print("End:", skyguard["timestamp"].max())

Timestamp dtype: datetime64[us, UTC]
Invalid timestamps: 0
Start: 2024-01-01 00:00:00+00:00
End: 2029-09-14 07:00:00+00:00

In [41]:
print("Duplicate rows:", skyguard.duplicated().sum())

print("\nMissing values:")
print(skyguard.isna().sum())

Duplicate rows: 0

Missing values:
timestamp                   0
station_id                  0
station_name                0
latitude                    0
longitude                   0
temperature_C            2759
pressure_hPa             2652
relative_humidity_pct    2602
anomaly                     0
anomaly_type                0
severity                    0
injected                    0
dtype: int64

In [42]:
numeric_columns = [
    "latitude",
    "longitude",
    "temperature_C",
    "pressure_hPa",
    "relative_humidity_pct"
]

print(
    skyguard[numeric_columns].describe().T
)

                           count         mean        std         min      25%  \
latitude               1000000.0    22.688253   6.163848    9.930000    18.52
longitude              1000000.0    79.416587   5.151605   72.570000    75.79
temperature_C           997241.0    26.776012   6.439977  -15.816456    22.12
pressure_hPa            997348.0  1006.387462   7.264963  919.900246  1002.20
relative_humidity_pct   997398.0    67.211574  11.375101    0.000000    59.82

                           50%      75%          max
latitude                 23.02    26.85    34.080000
longitude                78.03    85.14    91.740000
temperature_C            26.83    31.33    68.184096
pressure_hPa           1006.26  1010.33  1089.868157
relative_humidity_pct    67.53    75.10   121.678486

In [43]:
# Create a working copy
skyguard_clean = skyguard.copy()

# Temperature plausibility flag
skyguard_clean["temperature_valid"] = (
    skyguard_clean["temperature_C"].between(-50, 60)
)

# Pressure plausibility flag
skyguard_clean["pressure_valid"] = (
    skyguard_clean["pressure_hPa"].between(870, 1085)
)

# Relative humidity plausibility flag
skyguard_clean["humidity_valid"] = (
    skyguard_clean["relative_humidity_pct"].between(0, 100)
)

# Missing-value flag
skyguard_clean["has_missing_weather"] = (
    skyguard_clean[
        [
            "temperature_C",
            "pressure_hPa",
            "relative_humidity_pct"
        ]
    ].isna().any(axis=1)
)

print("Temperature invalid:",
      (~skyguard_clean["temperature_valid"]).sum())

print("Pressure invalid:",
      (~skyguard_clean["pressure_valid"]).sum())

print("Humidity invalid:",
      (~skyguard_clean["humidity_valid"]).sum())

print("Rows with missing weather:",
      skyguard_clean["has_missing_weather"].sum())

Temperature invalid: 3031
Pressure invalid: 2666
Humidity invalid: 2776
Rows with missing weather: 8013

In [44]:
skyguard_clean["temperature_C_clean"] = (
    skyguard_clean["temperature_C"]
    .where(skyguard_clean["temperature_valid"])
)

skyguard_clean["pressure_hPa_clean"] = (
    skyguard_clean["pressure_hPa"]
    .where(skyguard_clean["pressure_valid"])
)

skyguard_clean["relative_humidity_pct_clean"] = (
    skyguard_clean["relative_humidity_pct"]
    .where(skyguard_clean["humidity_valid"])
)

print("Cleaned columns created successfully ✅")

Cleaned columns created successfully ✅

In [45]:
print(
    skyguard_clean[
        [
            "temperature_C_clean",
            "pressure_hPa_clean",
            "relative_humidity_pct_clean"
        ]
    ].describe().T
)

                                count         mean        std         min  \
temperature_C_clean          996969.0    26.766225   6.413450  -15.816456
pressure_hPa_clean           997334.0  1006.386330   7.258726  919.900246
relative_humidity_pct_clean  997224.0    67.205168  11.365622    0.000000

                                 25%      50%      75%          max
temperature_C_clean            22.12    26.83    31.33    59.992010
pressure_hPa_clean           1002.20  1006.26  1010.33  1084.594343
relative_humidity_pct_clean    59.82    67.53    75.10   100.000000

In [46]:
import xarray as xr
import numpy as np
import pandas as pd

era5_file = "/content/era5_data/era5_2024_02.nc"

ds = xr.open_dataset(era5_file)

# ERA5 temperature: Kelvin → Celsius
ds["temperature_C"] = ds["t2m"] - 273.15

# ERA5 pressure: Pascal → hPa
ds["pressure_hPa"] = ds["sp"] / 100.0

# Dew point remains in Kelvin for the humidity calculation
# Calculate relative humidity using the Magnus approximation

T = ds["t2m"] - 273.15
Td = ds["d2m"] - 273.15

a = 17.625
b = 243.04

gamma_T = (a * T) / (b + T)
gamma_Td = (a * Td) / (b + Td)

ds["relative_humidity_pct"] = (
    100.0 * np.exp(gamma_Td - gamma_T)
)

print("✅ ERA5 conversion complete")

print("\nVariables:")
print(list(ds.data_vars))

print("\nTemperature:")
print(
    float(ds["temperature_C"].min()),
    "to",
    float(ds["temperature_C"].max()),
    "°C"
)

print("\nPressure:")
print(
    float(ds["pressure_hPa"].min()),
    "to",
    float(ds["pressure_hPa"].max()),
    "hPa"
)

print("\nRelative humidity:")
print(
    float(ds["relative_humidity_pct"].min()),
    "to",
    float(ds["relative_humidity_pct"].max()),
    "%"
)

✅ ERA5 conversion complete

Variables:
['t2m', 'd2m', 'sp', 'temperature_C', 'pressure_hPa', 'relative_humidity_pct']

Temperature:
-42.83148193359375 to 39.523956298828125 °C

Pressure:
497.6986389160156 to 1023.192626953125 hPa

Relative humidity:
2.023552179336548 to 100.02046966552734 %

In [47]:
import xarray as xr
import numpy as np
import os

processed_dir = "/content/era5_processed"
os.makedirs(processed_dir, exist_ok=True)

era5_files = sorted(
    f for f in os.listdir("/content/era5_data")
    if f.endswith(".nc")
)

def process_era5_file(input_file, output_file):

    ds = xr.open_dataset(input_file)

    # Kelvin → Celsius
    ds["temperature_C"] = ds["t2m"] - 273.15

    # Pascal → hPa
    ds["pressure_hPa"] = ds["sp"] / 100.0

    # Temperature and dew point in Celsius
    T = ds["t2m"] - 273.15
    Td = ds["d2m"] - 273.15

    # Magnus formula
    a = 17.625
    b = 243.04

    gamma_T = (a * T) / (b + T)
    gamma_Td = (a * Td) / (b + Td)

    rh = 100.0 * np.exp(gamma_Td - gamma_T)

    # Prevent tiny numerical overshoots
    ds["relative_humidity_pct"] = rh.clip(
        min=0,
        max=100
    )

    # Keep only the variables we need
    ds = ds[
        [
            "temperature_C",
            "pressure_hPa",
            "relative_humidity_pct"
        ]
    ]

    ds.to_netcdf(output_file)

    ds.close()


for i, filename in enumerate(era5_files, start=1):

    input_path = os.path.join(
        "/content/era5_data",
        filename
    )

    output_filename = filename.replace(
        ".nc",
        "_processed.nc"
    )

    output_path = os.path.join(
        processed_dir,
        output_filename
    )

    if os.path.exists(output_path):

        print(
            f"⏭️ {i}/{len(era5_files)} "
            f"{filename} already processed"
        )

        continue

    print(
        f"🔄 Processing {i}/{len(era5_files)}: "
        f"{filename}"
    )

    process_era5_file(
        input_path,
        output_path
    )

    print("   ✅ Done")


print("\n🎉 All ERA5 files processed!")

🔄 Processing 1/30: era5_2024_01.nc
   ✅ Done
🔄 Processing 2/30: era5_2024_02.nc
   ✅ Done
🔄 Processing 3/30: era5_2024_03.nc
   ✅ Done
🔄 Processing 4/30: era5_2024_04.nc
   ✅ Done
🔄 Processing 5/30: era5_2024_05.nc
   ✅ Done
🔄 Processing 6/30: era5_2024_06.nc
   ✅ Done
🔄 Processing 7/30: era5_2024_07.nc
   ✅ Done
🔄 Processing 8/30: era5_2024_08.nc
   ✅ Done
🔄 Processing 9/30: era5_2024_09.nc
   ✅ Done
🔄 Processing 10/30: era5_2024_10.nc
   ✅ Done
🔄 Processing 11/30: era5_2024_11.nc
   ✅ Done
🔄 Processing 12/30: era5_2024_12.nc
   ✅ Done
🔄 Processing 13/30: era5_2025_01.nc
   ✅ Done
🔄 Processing 14/30: era5_2025_02.nc
   ✅ Done
🔄 Processing 15/30: era5_2025_03.nc
   ✅ Done
🔄 Processing 16/30: era5_2025_04.nc
   ✅ Done
🔄 Processing 17/30: era5_2025_05.nc
   ✅ Done
🔄 Processing 18/30: era5_2025_06.nc
   ✅ Done
🔄 Processing 19/30: era5_2025_07.nc
   ✅ Done
🔄 Processing 20/30: era5_2025_08.nc
   ✅ Done
🔄 Processing 21/30: era5_2025_09.nc
   ✅ Done
🔄 Processing 22/30: era5_2025_10.nc
   ✅ Done
🔄 Processing 23/30: era5_2025_11.nc
   ✅ Done
🔄 Processing 24/30: era5_2025_12.nc
   ✅ Done
🔄 Processing 25/30: era5_2026_01.nc
   ✅ Done
🔄 Processing 26/30: era5_2026_02.nc
   ✅ Done
🔄 Processing 27/30: era5_2026_03.nc
   ✅ Done
🔄 Processing 28/30: era5_2026_04.nc
   ✅ Done
🔄 Processing 29/30: era5_2026_05.nc
   ✅ Done
🔄 Processing 30/30: era5_2026_06.nc
   ✅ Done

🎉 All ERA5 files processed!

In [48]:
import os

processed_files = sorted(
    f for f in os.listdir("/content/era5_processed")
    if f.endswith(".nc")
)

print("Processed ERA5 files:", len(processed_files))

for f in processed_files:
    print(f)

Processed ERA5 files: 30
era5_2024_01_processed.nc
era5_2024_02_processed.nc
era5_2024_03_processed.nc
era5_2024_04_processed.nc
era5_2024_05_processed.nc
era5_2024_06_processed.nc
era5_2024_07_processed.nc
era5_2024_08_processed.nc
era5_2024_09_processed.nc
era5_2024_10_processed.nc
era5_2024_11_processed.nc
era5_2024_12_processed.nc
era5_2025_01_processed.nc
era5_2025_02_processed.nc
era5_2025_03_processed.nc
era5_2025_04_processed.nc
era5_2025_05_processed.nc
era5_2025_06_processed.nc
era5_2025_07_processed.nc
era5_2025_08_processed.nc
era5_2025_09_processed.nc
era5_2025_10_processed.nc
era5_2025_11_processed.nc
era5_2025_12_processed.nc
era5_2026_01_processed.nc
era5_2026_02_processed.nc
era5_2026_03_processed.nc
era5_2026_04_processed.nc
era5_2026_05_processed.nc
era5_2026_06_processed.nc

In [49]:
import pandas as pd
import numpy as np

# Work from our cleaned dataset
hybrid_df = skyguard_clean.copy()

# Keep only observations for which ERA5 exists
ERA5_END = pd.Timestamp(
    "2026-06-25 23:00:00",
    tz="UTC"
)

hybrid_df = hybrid_df[
    hybrid_df["timestamp"] <= ERA5_END
].copy()

print("Rows before ERA5 matching:", len(hybrid_df))

print("Start:", hybrid_df["timestamp"].min())
print("End:", hybrid_df["timestamp"].max())

Rows before ERA5 matching: 435360
Start: 2024-01-01 00:00:00+00:00
End: 2026-06-25 23:00:00+00:00

In [50]:
hybrid_df["era5_latitude"] = (
    np.round(hybrid_df["latitude"] * 4) / 4
)

hybrid_df["era5_longitude"] = (
    np.round(hybrid_df["longitude"] * 4) / 4
)

print(
    hybrid_df[
        [
            "station_id",
            "latitude",
            "longitude",
            "era5_latitude",
            "era5_longitude"
        ]
    ]
    .drop_duplicates()
    .sort_values("station_id")
    .to_string(index=False)
)

station_id  latitude  longitude  era5_latitude  era5_longitude
     ST001     28.61      77.21          28.50           77.25
     ST002     26.85      80.95          26.75           81.00
     ST003     19.08      72.88          19.00           73.00
     ST004     22.57      88.36          22.50           88.25
     ST005     13.08      80.27          13.00           80.25
     ST006     12.97      77.59          13.00           77.50
     ST007     17.39      78.49          17.50           78.50
     ST008     26.91      75.79          27.00           75.75
     ST009     25.59      85.14          25.50           85.25
     ST010     23.26      77.41          23.25           77.50
     ST011     23.02      72.57          23.00           72.50
     ST012     18.52      73.86          18.50           73.75
     ST013     20.30      85.82          20.25           85.75
     ST014     26.14      91.74          26.25           91.75
     ST015     34.08      74.80          34.00           74.75
     ST016     30.73      76.78          30.75           76.75
     ST017      9.93      76.27          10.00           76.25
     ST018     21.15      79.09          21.25           79.00
     ST019     23.34      85.31          23.25           85.25
     ST020     30.32      78.03          30.25           78.00

In [51]:
import os

HYBRID_DIR = "/content/hybrid_monthly"

os.makedirs(HYBRID_DIR, exist_ok=True)

print("✅ Hybrid output folder ready")

✅ Hybrid output folder ready

In [52]:
import xarray as xr
import pandas as pd
import numpy as np

era5_file = "/content/era5_processed/era5_2024_02_processed.nc"

ds = xr.open_dataset(era5_file)

print(ds)

<xarray.Dataset> Size: 63MB
Dimensions:                (valid_time: 696, latitude: 97, longitude: 78)
Coordinates:
  * valid_time             (valid_time) datetime64[ns] 6kB 2024-02-01 ... 202...
    expver                 (valid_time) <U4 11kB ...
  * latitude               (latitude) float64 776B 34.0 33.75 ... 10.25 10.0
  * longitude              (longitude) float64 624B 72.5 72.75 ... 91.5 91.75
    number                 int64 8B ...
Data variables:
    temperature_C          (valid_time, latitude, longitude) float32 21MB ...
    pressure_hPa           (valid_time, latitude, longitude) float32 21MB ...
    relative_humidity_pct  (valid_time, latitude, longitude) float32 21MB ...
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-08-23T13:48 GRIB to CDM+CF via cfgrib-0.9.1...

In [53]:
# Convert ERA5 data to a DataFrame
era5_month = ds[
    [
        "temperature_C",
        "pressure_hPa",
        "relative_humidity_pct"
    ]
].to_dataframe().reset_index()

print("ERA5 rows:", len(era5_month))
print("Columns:", era5_month.columns.tolist())

display(era5_month.head())

ERA5 rows: 5265936
Columns: ['valid_time', 'latitude', 'longitude', 'temperature_C', 'pressure_hPa', 'relative_humidity_pct', 'number', 'expver']

,valid_time,latitude,longitude,temperature_C,pressure_hPa,relative_humidity_pct,number,expver
0,2024-02-01,34.0,72.50,8.854736,963.870789,93.993011,0,0001
1,2024-02-01,34.0,72.75,8.772705,948.960754,89.598030,0,0001
2,2024-02-01,34.0,73.00,7.235596,910.730774,85.129532,0,0001
3,2024-02-01,34.0,73.25,3.454346,875.430786,92.275719,0,0001
4,2024-02-01,34.0,73.50,1.677002,859.630798,91.635910,0,0001

In [54]:
grid_points = stations[
    ["station_id", "era5_latitude", "era5_longitude"]
].copy()

era5_month = era5_month.merge(
    grid_points,
    left_on=["latitude", "longitude"],
    right_on=["era5_latitude", "era5_longitude"],
    how="inner"
)

print("ERA5 rows after station filtering:", len(era5_month))

print(
    era5_month["station_id"]
    .nunique(),
    "stations found"
)

ERA5 rows after station filtering: 13920
20 stations found

In [55]:
era5_month["valid_time"] = pd.to_datetime(
    era5_month["valid_time"],
    utc=True
)

era5_month = era5_month.sort_values(
    ["station_id", "valid_time"]
)

print(
    era5_month[
        [
            "station_id",
            "valid_time",
            "temperature_C",
            "pressure_hPa",
            "relative_humidity_pct"
        ]
    ].head(10)
)

    station_id                valid_time  temperature_C  pressure_hPa  \
3        ST001 2024-02-01 00:00:00+00:00      14.118408    987.440796
23       ST001 2024-02-01 01:00:00+00:00      14.169830    987.968567
43       ST001 2024-02-01 02:00:00+00:00      14.293243    988.885803
63       ST001 2024-02-01 03:00:00+00:00      14.247650    989.727173
83       ST001 2024-02-01 04:00:00+00:00      14.269958    990.348389
103      ST001 2024-02-01 05:00:00+00:00      16.211395    991.046265
123      ST001 2024-02-01 06:00:00+00:00      17.655426    990.799927
143      ST001 2024-02-01 07:00:00+00:00      18.113678    990.156433
163      ST001 2024-02-01 08:00:00+00:00      19.712372    989.582581
183      ST001 2024-02-01 09:00:00+00:00      20.248840    988.869873

     relative_humidity_pct
3                98.827927
23               98.500732
43               97.878975
63               98.223511
83               97.484596
103              88.915894
123              85.127342
143              81.768562
163              74.469337
183              72.094086

In [56]:
# Select February 2024 SkyGuard observations
sky_feb = hybrid_df[
    (hybrid_df["timestamp"] >= "2024-02-01 00:00:00+00:00") &
    (hybrid_df["timestamp"] <  "2024-03-01 00:00:00+00:00")
].copy()

print("SkyGuard February rows:", len(sky_feb))

print(
    "Stations:",
    sky_feb["station_id"].nunique()
)

print(
    "Time range:",
    sky_feb["timestamp"].min(),
    "→",
    sky_feb["timestamp"].max()
)

SkyGuard February rows: 13920
Stations: 20
Time range: 2024-02-01 00:00:00+00:00 → 2024-02-29 23:00:00+00:00

In [57]:
sky_feb = sky_feb.sort_values(
    ["station_id", "timestamp"]
).reset_index(drop=True)

era5_month = era5_month.sort_values(
    ["station_id", "valid_time"]
).reset_index(drop=True)

print("✅ Both datasets sorted")

✅ Both datasets sorted

In [58]:
# Make both timestamp columns exactly the same dtype

sky_feb["timestamp"] = pd.to_datetime(
    sky_feb["timestamp"],
    utc=True
).astype("datetime64[ns, UTC]")

era5_month["valid_time"] = pd.to_datetime(
    era5_month["valid_time"],
    utc=True
).astype("datetime64[ns, UTC]")

print("SkyGuard dtype:", sky_feb["timestamp"].dtype)
print("ERA5 dtype:", era5_month["valid_time"].dtype)

SkyGuard dtype: datetime64[ns, UTC]
ERA5 dtype: datetime64[ns, UTC]

In [59]:
# Make completely independent copies
sky_feb_sorted = sky_feb.copy()
era5_month_sorted = era5_month.copy()

# Make sure timestamps have exactly the same dtype
sky_feb_sorted["timestamp"] = pd.to_datetime(
    sky_feb_sorted["timestamp"],
    utc=True
).astype("datetime64[ns, UTC]")

era5_month_sorted["valid_time"] = pd.to_datetime(
    era5_month_sorted["valid_time"],
    utc=True
).astype("datetime64[ns, UTC]")

# IMPORTANT:
# merge_asof requires the merge keys themselves to be globally sorted.
sky_feb_sorted = sky_feb_sorted.sort_values(
    "timestamp"
).reset_index(drop=True)

era5_month_sorted = era5_month_sorted.sort_values(
    "valid_time"
).reset_index(drop=True)

print("SkyGuard sorted:", sky_feb_sorted["timestamp"].is_monotonic_increasing)
print("ERA5 sorted:", era5_month_sorted["valid_time"].is_monotonic_increasing)

SkyGuard sorted: True
ERA5 sorted: True

In [60]:
matched_feb = pd.merge_asof(
    sky_feb_sorted,
    era5_month_sorted[
        [
            "station_id",
            "valid_time",
            "temperature_C",
            "pressure_hPa",
            "relative_humidity_pct"
        ]
    ],
    left_on="timestamp",
    right_on="valid_time",
    by="station_id",
    direction="nearest",
    tolerance=pd.Timedelta("30min"),
    suffixes=("_skyguard", "_era5")
)

print("Matched February rows:", len(matched_feb))

print(
    "Rows with ERA5 match:",
    matched_feb["valid_time"].notna().sum()
)

print(
    "Rows without ERA5 match:",
    matched_feb["valid_time"].isna().sum()
)

Matched February rows: 13920
Rows with ERA5 match: 13920
Rows without ERA5 match: 0

In [61]:
# ==============================
# HYBRID FEATURE ENGINEERING
# ==============================

matched_feb["temperature_difference"] = (
    matched_feb["temperature_C_skyguard"]
    - matched_feb["temperature_C_era5"]
)

matched_feb["pressure_difference"] = (
    matched_feb["pressure_hPa_skyguard"]
    - matched_feb["pressure_hPa_era5"]
)

matched_feb["humidity_difference"] = (
    matched_feb["relative_humidity_pct_skyguard"]
    - matched_feb["relative_humidity_pct_era5"]
)

print("✅ Hybrid comparison features created")

display(
    matched_feb[
        [
            "station_id",
            "timestamp",
            "temperature_C_skyguard",
            "temperature_C_era5",
            "temperature_difference",
            "pressure_hPa_skyguard",
            "pressure_hPa_era5",
            "pressure_difference",
            "relative_humidity_pct_skyguard",
            "relative_humidity_pct_era5",
            "humidity_difference"
        ]
    ].head(10)
)

✅ Hybrid comparison features created

,station_id,timestamp,temperature_C_skyguard,temperature_C_era5,temperature_difference,pressure_hPa_skyguard,pressure_hPa_era5,pressure_difference,relative_humidity_pct_skyguard,relative_humidity_pct_era5,humidity_difference
0,ST001,2024-02-01 00:00:00+00:00,18.06,14.118408,3.941592,1008.34,987.440796,20.899204,79.28,98.827927,-19.547927
1,ST019,2024-02-01 00:00:00+00:00,16.65,15.665283,0.984717,1011.00,943.420776,67.579224,78.39,91.635422,-13.245422
2,ST019,2024-02-01 00:00:00+00:00,18.01,15.665283,2.344717,1007.77,943.420776,64.349224,76.91,91.635422,-14.725422
3,ST019,2024-02-01 00:00:00+00:00,15.91,15.665283,0.244717,1006.66,943.420776,63.239224,81.29,91.635422,-10.345422
4,ST018,2024-02-01 00:00:00+00:00,18.95,18.118408,0.831592,1007.83,975.030762,32.799238,76.11,85.605408,-9.495408
5,ST017,2024-02-01 00:00:00+00:00,16.99,26.425049,-9.435049,1015.88,1009.560791,6.319209,83.80,82.242317,1.557683
6,ST005,2024-02-01 00:00:00+00:00,17.58,25.788330,-8.208330,1015.59,1012.790771,2.799229,76.43,86.391037,-9.961037
7,ST016,2024-02-01 00:00:00+00:00,16.03,12.825439,3.204561,1005.04,965.870789,39.169211,82.70,83.193901,-0.493901
8,ST002,2024-02-01 00:00:00+00:00,15.32,13.458252,1.861748,1001.28,1000.720764,0.559236,76.59,89.401566,-12.811566
9,ST015,2024-02-01 00:00:00+00:00,17.75,-0.026123,17.776123,1002.22,809.960754,192.259246,77.37,96.676514,-19.306514

In [62]:
difference_columns = [
    "temperature_difference",
    "pressure_difference",
    "humidity_difference"
]

print(
    matched_feb[difference_columns].describe().T
)

                          count       mean        std        min       25%  \
temperature_difference  13891.0   2.215536   7.122949 -35.193522 -2.357174
pressure_difference     13891.0  34.309242  45.973879 -68.724122 -0.564453
humidity_difference     13874.0  11.095704  19.884870 -98.708862 -4.026761

                              50%        75%         max
temperature_difference   1.321180   5.591881   37.695949
pressure_difference     24.816086  59.667439  256.188204
humidity_difference     10.089499  25.618880   76.422541

In [63]:
station_check = (
    matched_feb
    .groupby("station_id")[
        [
            "temperature_difference",
            "pressure_difference",
            "humidity_difference"
        ]
    ]
    .agg(["mean", "median", "std"])
)

display(station_check)

           temperature_difference                      pressure_difference  \
                             mean     median       std                mean
station_id
ST001                    5.721191   5.781050  4.404901           11.697139
ST002                    4.804600   4.976064  4.257559            1.182090
ST003                   -2.353297  -2.415745  4.493035           -2.075880
ST004                    0.376665   0.334884  4.027625           -7.772271
ST005                   -4.655070  -4.906576  3.769292           -0.596908
ST006                   -2.338765  -2.022224  4.277666           94.043293
ST007                   -2.725243  -2.671102  4.102462           58.475528
ST008                    4.831648   4.881957  4.459916           34.852084
ST009                    3.782547   3.562733  4.033346           -5.342541
ST010                    2.049003   2.139297  3.599343           45.284087
ST011                   -0.418517  -0.375699  3.806261           -3.769824
ST012                    0.271733   0.681875  4.903952           73.661870
ST013                   -1.956268  -1.935604  4.324532           -2.325827
ST014                    3.037046   2.951779  3.673588            6.449304
ST015                   20.652219  20.988666  4.147498          181.668014
ST016                    7.165669   7.297435  4.708801           31.041531
ST017                   -5.857379  -6.196979  3.747252            6.461176
ST018                   -0.948308  -1.031652  4.076772           30.787753
ST019                    3.640794   3.406538  4.072955           61.251917
ST020                    8.779285   8.804808  4.272785           67.323786

                                 humidity_difference
                median       std                mean     median        std
station_id
ST001        11.815640  5.123780            8.562626   6.058231  21.316996
ST002         1.276245  5.393359            8.280094   6.712634  20.073637
ST003        -2.161885  6.468500           14.054682  13.714715  15.976642
ST004        -8.058170  6.413724            2.734302  -1.112747  18.463328
ST005        -0.698574  5.422001            0.206863  -0.744567  11.708640
ST006        94.204697  5.469359           22.631185  25.571051  22.613954
ST007        58.647983  5.032217           19.009674  21.054591  19.314099
ST008        35.012368  5.107795           20.595681  21.095785  19.693800
ST009        -5.382013  4.561710            2.709869  -0.109862  18.904344
ST010        45.362266  6.505174           14.969951  15.490462  17.646222
ST011        -3.750909  7.276284           25.159524  26.035865  15.611251
ST012        73.694360  5.236922           24.185245  23.765775  17.565408
ST013        -2.699894  5.330998            2.226107   0.457469  18.480134
ST014         6.620118  4.624829            1.846300  -0.901330  17.435880
ST015       181.030264  5.900492           11.198493  10.512525  18.473410
ST016        31.415654  6.184395            7.233080   5.193157  18.341142
ST017         6.492485  5.499295            1.053231   0.796478  10.545091
ST018        30.652041  3.902811           16.559845  17.065864  17.910896
ST019        61.013367  5.335867           11.797364  12.803493  19.428461
ST020        67.323579  4.727157            6.565412   4.684555  20.543511

In [64]:
station_counts = (
    matched_feb
    .groupby("station_id")
    .size()
    .sort_values()
)

print("Rows per station:")
print(station_counts)

Rows per station:
station_id
ST005    658
ST009    663
ST012    669
ST013    670
ST019    671
ST002    676
ST018    685
ST001    688
ST011    690
ST010    693
ST014    695
ST020    695
ST008    702
ST007    707
ST015    709
ST017    713
ST006    715
ST003    731
ST004    744
ST016    746
dtype: int64

In [65]:
print("Largest temperature differences:")

display(
    matched_feb[
        [
            "station_id",
            "timestamp",
            "temperature_C_skyguard",
            "temperature_C_era5",
            "temperature_difference"
        ]
    ]
    .sort_values(
        "temperature_difference",
        ascending=False
    )
    .head(10)
)

Largest temperature differences:

,station_id,timestamp,temperature_C_skyguard,temperature_C_era5,temperature_difference
6335,ST015,2024-02-14 04:00:00+00:00,35.963253,-1.732697,37.695949
11381,ST016,2024-02-24 17:00:00+00:00,46.768376,11.686890,35.081486
6268,ST008,2024-02-14 01:00:00+00:00,49.038502,14.274445,34.764057
4869,ST016,2024-02-11 03:00:00+00:00,44.155112,10.204803,33.950308
405,ST016,2024-02-01 20:00:00+00:00,45.365298,11.426666,33.938632
369,ST015,2024-02-01 18:00:00+00:00,33.119393,-0.556305,33.675698
4184,ST001,2024-02-09 17:00:00+00:00,44.815667,11.589020,33.226647
5895,ST015,2024-02-13 06:00:00+00:00,36.431184,3.272736,33.158449
4342,ST016,2024-02-10 01:00:00+00:00,40.959451,8.563782,32.395669
13311,ST009,2024-02-28 17:00:00+00:00,52.543943,20.313232,32.230711

In [66]:
print("Largest pressure differences:")

display(
    matched_feb[
        [
            "station_id",
            "timestamp",
            "pressure_hPa_skyguard",
            "pressure_hPa_era5",
            "pressure_difference"
        ]
    ]
    .sort_values(
        "pressure_difference",
        ascending=False
    )
    .head(10)
)

Largest pressure differences:

,station_id,timestamp,pressure_hPa_skyguard,pressure_hPa_era5,pressure_difference
1673,ST015,2024-02-04 11:00:00+00:00,1068.745760,812.557556,256.188204
8746,ST015,2024-02-19 05:00:00+00:00,1015.357062,808.188416,207.168646
12999,ST015,2024-02-28 01:00:00+00:00,1019.910000,818.391541,201.518459
9923,ST015,2024-02-21 16:00:00+00:00,1013.733164,812.887024,200.846140
1061,ST015,2024-02-03 05:00:00+00:00,1011.470000,817.077637,194.392363
8875,ST015,2024-02-19 11:00:00+00:00,998.770000,804.724365,194.045635
2000,ST015,2024-02-05 04:00:00+00:00,1009.220000,815.871643,193.348357
171,ST015,2024-02-01 08:00:00+00:00,1003.270000,810.662598,192.607402
188,ST015,2024-02-01 09:00:00+00:00,1002.540000,810.189819,192.350181
8887,ST015,2024-02-19 12:00:00+00:00,997.130000,804.842041,192.287959

In [67]:
station_pressure = (
    matched_feb
    .groupby("station_id")["pressure_difference"]
    .agg(
        mean="mean",
        median="median",
        std="std",
        min="min",
        max="max",
        count="count"
    )
    .sort_values("mean", ascending=False)
)

display(station_pressure)

                  mean      median       std         min         max  count
station_id
ST015       181.668014  181.030264  5.900492  124.765108  256.188204    709
ST006        94.043293   94.204697  5.469359   35.305861  120.612974    715
ST012        73.661870   73.694360  5.236922   17.913992  121.019345    669
ST020        67.323786   67.323579  4.727157   26.921292  109.074137    695
ST019        61.251917   61.013367  5.335867   31.837012  120.224186    669
ST007        58.475528   58.647983  5.032217   -2.605846   87.351877    703
ST010        45.284087   45.362266  6.505174  -26.510703  104.991868    690
ST008        34.852084   35.012368  5.107795  -31.909296   80.182125    701
ST016        31.041531   31.415654  6.184395  -30.220734  101.501390    745
ST018        30.787753   30.652041  3.902811   20.526899   67.506557    684
ST001        11.697139   11.815640  5.123780  -44.377017   45.295895    686
ST017         6.461176    6.492485  5.499295  -46.062847   55.764538    710
ST014         6.449304    6.620118  4.624829  -41.717461   29.871240    694
ST002         1.182090    1.276245  5.393359  -66.897943   55.235813    673
ST005        -0.596908   -0.698574  5.422001  -68.724122   54.687713    657
ST003        -2.075880   -2.161885  6.468500  -60.110660   45.490453    731
ST013        -2.325827   -2.699894  5.330998  -13.171846   63.884325    670
ST011        -3.769824   -3.750909  7.276284  -65.535704   61.991377    688
ST009        -5.342541   -5.382013  4.561710  -15.255967   31.720874    660
ST004        -7.772271   -8.058170  6.413724  -49.691169   59.754890    742

In [68]:
print(
    stations[
        [
            "station_id",
            "station_name",
            "latitude",
            "longitude"
        ]
    ].sort_values("station_id").to_string(index=False)
)

station_id station_name  latitude  longitude
     ST001        Delhi     28.61      77.21
     ST002      Lucknow     26.85      80.95
     ST003       Mumbai     19.08      72.88
     ST004      Kolkata     22.57      88.36
     ST005      Chennai     13.08      80.27
     ST006    Bengaluru     12.97      77.59
     ST007    Hyderabad     17.39      78.49
     ST008       Jaipur     26.91      75.79
     ST009        Patna     25.59      85.14
     ST010       Bhopal     23.26      77.41
     ST011    Ahmedabad     23.02      72.57
     ST012         Pune     18.52      73.86
     ST013  Bhubaneswar     20.30      85.82
     ST014     Guwahati     26.14      91.74
     ST015     Srinagar     34.08      74.80
     ST016   Chandigarh     30.73      76.78
     ST017        Kochi      9.93      76.27
     ST018       Nagpur     21.15      79.09
     ST019       Ranchi     23.34      85.31
     ST020     Dehradun     30.32      78.03

In [69]:
station_pressure = (
    matched_feb
    .groupby("station_id")["pressure_difference"]
    .agg(
        mean="mean",
        median="median",
        std="std",
        min="min",
        max="max",
        count="count"
    )
    .sort_values("mean", ascending=False)
)

display(station_pressure)

                  mean      median       std         min         max  count
station_id
ST015       181.668014  181.030264  5.900492  124.765108  256.188204    709
ST006        94.043293   94.204697  5.469359   35.305861  120.612974    715
ST012        73.661870   73.694360  5.236922   17.913992  121.019345    669
ST020        67.323786   67.323579  4.727157   26.921292  109.074137    695
ST019        61.251917   61.013367  5.335867   31.837012  120.224186    669
ST007        58.475528   58.647983  5.032217   -2.605846   87.351877    703
ST010        45.284087   45.362266  6.505174  -26.510703  104.991868    690
ST008        34.852084   35.012368  5.107795  -31.909296   80.182125    701
ST016        31.041531   31.415654  6.184395  -30.220734  101.501390    745
ST018        30.787753   30.652041  3.902811   20.526899   67.506557    684
ST001        11.697139   11.815640  5.123780  -44.377017   45.295895    686
ST017         6.461176    6.492485  5.499295  -46.062847   55.764538    710
ST014         6.449304    6.620118  4.624829  -41.717461   29.871240    694
ST002         1.182090    1.276245  5.393359  -66.897943   55.235813    673
ST005        -0.596908   -0.698574  5.422001  -68.724122   54.687713    657
ST003        -2.075880   -2.161885  6.468500  -60.110660   45.490453    731
ST013        -2.325827   -2.699894  5.330998  -13.171846   63.884325    670
ST011        -3.769824   -3.750909  7.276284  -65.535704   61.991377    688
ST009        -5.342541   -5.382013  4.561710  -15.255967   31.720874    660
ST004        -7.772271   -8.058170  6.413724  -49.691169   59.754890    742

In [70]:
# ==========================================
# STEP 9 — STATION PRESSURE BASELINE
# ==========================================

station_pressure_baseline = (
    matched_feb
    .groupby("station_id")["pressure_difference"]
    .median()
    .rename("station_pressure_baseline")
    .reset_index()
)

print("Station pressure baselines:")

display(
    station_pressure_baseline
    .sort_values("station_id")
)

Station pressure baselines:

   station_id  station_pressure_baseline
0       ST001                  11.815640
1       ST002                   1.276245
2       ST003                  -2.161885
3       ST004                  -8.058170
4       ST005                  -0.698574
5       ST006                  94.204697
6       ST007                  58.647983
7       ST008                  35.012368
8       ST009                  -5.382013
9       ST010                  45.362266
10      ST011                  -3.750909
11      ST012                  73.694360
12      ST013                  -2.699894
13      ST014                   6.620118
14      ST015                 181.030264
15      ST016                  31.415654
16      ST017                   6.492485
17      ST018                  30.652041
18      ST019                  61.013367
19      ST020                  67.323579

In [71]:
matched_feb = matched_feb.merge(
    station_pressure_baseline,
    on="station_id",
    how="left"
)

matched_feb["normalized_pressure_difference"] = (
    matched_feb["pressure_difference"]
    - matched_feb["station_pressure_baseline"]
)

print("✅ Normalized pressure feature created")

display(
    matched_feb[
        [
            "station_id",
            "pressure_difference",
            "station_pressure_baseline",
            "normalized_pressure_difference"
        ]
    ].head(10)
)

✅ Normalized pressure feature created

,station_id,pressure_difference,station_pressure_baseline,normalized_pressure_difference
0,ST001,20.899204,11.815640,9.083564
1,ST019,67.579224,61.013367,6.565857
2,ST019,64.349224,61.013367,3.335857
3,ST019,63.239224,61.013367,2.225857
4,ST018,32.799238,30.652041,2.147197
5,ST017,6.319209,6.492485,-0.173276
6,ST005,2.799229,-0.698574,3.497803
7,ST016,39.169211,31.415654,7.753557
8,ST002,0.559236,1.276245,-0.717009
9,ST015,192.259246,181.030264,11.228982

In [72]:
print("SkyGuard full dataset:")
print("Start:", skyguard_clean["timestamp"].min())
print("End:", skyguard_clean["timestamp"].max())

print("\nHybrid-compatible period:")
print("Start:", hybrid_df["timestamp"].min())
print("End:", hybrid_df["timestamp"].max())

print("\nRows:")
print("Full SkyGuard:", len(skyguard_clean))
print("ERA5-compatible:", len(hybrid_df))

SkyGuard full dataset:
Start: 2024-01-01 00:00:00+00:00
End: 2029-09-14 07:00:00+00:00

Hybrid-compatible period:
Start: 2024-01-01 00:00:00+00:00
End: 2026-06-25 23:00:00+00:00

Rows:
Full SkyGuard: 1000000
ERA5-compatible: 435360

In [73]:
reference_df = hybrid_df[
    (hybrid_df["timestamp"] >= "2024-01-01 00:00:00+00:00") &
    (hybrid_df["timestamp"] <  "2025-01-01 00:00:00+00:00")
].copy()

print("Reference period rows:", len(reference_df))

print(
    "Reference period:",
    reference_df["timestamp"].min(),
    "→",
    reference_df["timestamp"].max()
)

Reference period rows: 175680
Reference period: 2024-01-01 00:00:00+00:00 → 2024-12-31 23:00:00+00:00

In [74]:
# ==========================================
# STEP 11 — 2024 REFERENCE BASELINES
# ==========================================

# We'll calculate these AFTER the complete 2024
# SkyGuard + ERA5 hybrid dataset is created.

print("2024 reference rows:", len(reference_df))

print("\n⚠️ Baselines will be calculated after")
print("the complete 2024 ERA5 matching is finished.")

2024 reference rows: 175680

⚠️ Baselines will be calculated after
the complete 2024 ERA5 matching is finished.

In [75]:
import os
import gc
import xarray as xr
import pandas as pd
import numpy as np

ERA5_PROCESSED_DIR = "/content/era5_processed"
HYBRID_DIR = "/content/hybrid_monthly"

os.makedirs(HYBRID_DIR, exist_ok=True)


def process_one_month(year, month, skyguard_data):

    month_str = f"{month:02d}"

    print(f"\n{'='*50}")
    print(f"Processing {year}-{month_str}")
    print(f"{'='*50}")

    # ------------------------------------------
    # 1. Select SkyGuard rows for this month
    # ------------------------------------------

    start = pd.Timestamp(
        f"{year}-{month_str}-01",
        tz="UTC"
    )

    if month == 12:
        end = pd.Timestamp(
            f"{year+1}-01-01",
            tz="UTC"
        )
    else:
        end = pd.Timestamp(
            f"{year}-{month+1:02d}-01",
            tz="UTC"
        )

    sky_month = skyguard_data[
        (skyguard_data["timestamp"] >= start) &
        (skyguard_data["timestamp"] < end)
    ].copy()

    if len(sky_month) == 0:
        print("⚠️ No SkyGuard rows.")
        return None

    print("SkyGuard rows:", len(sky_month))

    # ------------------------------------------
    # 2. Open ERA5
    # ------------------------------------------

    era5_file = os.path.join(
        ERA5_PROCESSED_DIR,
        f"era5_{year}_{month_str}_processed.nc"
    )

    if not os.path.exists(era5_file):
        print("❌ ERA5 file not found:", era5_file)
        return None

    ds = xr.open_dataset(era5_file)

    # ------------------------------------------
    # 3. Convert ERA5 to dataframe
    # ------------------------------------------

    era5_month = ds[
        [
            "temperature_C",
            "pressure_hPa",
            "relative_humidity_pct"
        ]
    ].to_dataframe().reset_index()

    ds.close()

    # ------------------------------------------
    # 4. Match ERA5 grid points to stations
    # ------------------------------------------

    grid_points = stations[
        [
            "station_id",
            "era5_latitude",
            "era5_longitude"
        ]
    ].drop_duplicates()

    era5_month = era5_month.merge(
        grid_points,
        left_on=["latitude", "longitude"],
        right_on=["era5_latitude", "era5_longitude"],
        how="inner"
    )

    # ------------------------------------------
    # 5. Prepare timestamps
    # ------------------------------------------

    sky_month["timestamp"] = pd.to_datetime(
        sky_month["timestamp"],
        utc=True
    ).astype("datetime64[ns, UTC]")

    era5_month["valid_time"] = pd.to_datetime(
        era5_month["valid_time"],
        utc=True
    ).astype("datetime64[ns, UTC]")

    # ------------------------------------------
    # 6. Sort for merge_asof
    # ------------------------------------------

    sky_month = sky_month.sort_values(
        "timestamp"
    ).reset_index(drop=True)

    era5_month = era5_month.sort_values(
        "valid_time"
    ).reset_index(drop=True)

    # ------------------------------------------
    # 7. Temporal matching
    # ------------------------------------------

    matched = pd.merge_asof(
        sky_month,
        era5_month[
            [
                "station_id",
                "valid_time",
                "temperature_C",
                "pressure_hPa",
                "relative_humidity_pct"
            ]
        ],
        left_on="timestamp",
        right_on="valid_time",
        by="station_id",
        direction="nearest",
        tolerance=pd.Timedelta("30min"),
        suffixes=("_skyguard", "_era5")
    )

    # ------------------------------------------
    # 8. Create hybrid differences
    # ------------------------------------------

    matched["temperature_difference"] = (
        matched["temperature_C_skyguard"]
        - matched["temperature_C_era5"]
    )

    matched["pressure_difference"] = (
        matched["pressure_hPa_skyguard"]
        - matched["pressure_hPa_era5"]
    )

    matched["humidity_difference"] = (
        matched["relative_humidity_pct_skyguard"]
        - matched["relative_humidity_pct_era5"]
    )

    # ------------------------------------------
    # 9. Matching quality flag
    # ------------------------------------------

    matched["era5_match"] = (
        matched["valid_time"].notna()
    )

    # ------------------------------------------
    # 10. Save monthly result
    # ------------------------------------------

    output_file = os.path.join(
        HYBRID_DIR,
        f"hybrid_{year}_{month_str}.parquet"
    )

    matched.to_parquet(
        output_file,
        index=False
    )

    print("Hybrid rows:", len(matched))
    print(
        "ERA5 matches:",
        matched["era5_match"].sum()
    )

    print(
        "Saved:",
        output_file
    )

    # Clean memory
    del sky_month
    del era5_month
    del matched

    gc.collect()

    return output_file

In [76]:
test_file = process_one_month(
    2024,
    1,
    hybrid_df
)

print("\nTest result:", test_file)

==================================================
Processing 2024-01
==================================================
SkyGuard rows: 14880
Hybrid rows: 14880
ERA5 matches: 14880
Saved: /content/hybrid_monthly/hybrid_2024_01.parquet

Test result: /content/hybrid_monthly/hybrid_2024_01.parquet

In [77]:
# ==========================================
# STEP 13 — PROCESS ALL REMAINING MONTHS
# ==========================================

successful = []
failed = []

for year in [2024, 2025, 2026]:

    # 2024 and 2025 → 12 months
    # 2026 → January through June
    max_month = 12 if year < 2026 else 6

    for month in range(1, max_month + 1):

        output_file = (
            f"/content/hybrid_monthly/"
            f"hybrid_{year}_{month:02d}.parquet"
        )

        # January 2024 already completed
        if os.path.exists(output_file):

            print(
                f"⏭️ Skipping {year}-{month:02d} "
                f"(already exists)"
            )

            successful.append(output_file)
            continue

        try:

            result = process_one_month(
                year,
                month,
                hybrid_df
            )

            if result is not None:
                successful.append(result)
            else:
                failed.append(f"{year}-{month:02d}")

        except Exception as e:

            print(
                f"❌ FAILED {year}-{month:02d}"
            )

            print("Error:", e)

            failed.append(
                f"{year}-{month:02d}"
            )

print("\n" + "="*50)
print("🎉 HYBRID PROCESSING FINISHED")
print("="*50)

print("\nSuccessful:", len(successful))
print("Failed:", len(failed))

if failed:
    print("\nFailed months:")
    print(failed)

⏭️ Skipping 2024-01 (already exists)

==================================================
Processing 2024-02
==================================================
SkyGuard rows: 13920
Hybrid rows: 13920
ERA5 matches: 13920
Saved: /content/hybrid_monthly/hybrid_2024_02.parquet

==================================================
Processing 2024-03
==================================================
SkyGuard rows: 14880
Hybrid rows: 14880
ERA5 matches: 14880
Saved: /content/hybrid_monthly/hybrid_2024_03.parquet

==================================================
Processing 2024-04
==================================================
SkyGuard rows: 14400
Hybrid rows: 14400
ERA5 matches: 14400
Saved: /content/hybrid_monthly/hybrid_2024_04.parquet

==================================================
Processing 2024-05
==================================================
SkyGuard rows: 14880
Hybrid rows: 14880
ERA5 matches: 14880
Saved: /content/hybrid_monthly/hybrid_2024_05.parquet

==================================================
Processing 2024-06
==================================================
SkyGuard rows: 14400
Hybrid rows: 14400
ERA5 matches: 14400
Saved: /content/hybrid_monthly/hybrid_2024_06.parquet

==================================================
Processing 2024-07
==================================================
SkyGuard rows: 14880
Hybrid rows: 14880
ERA5 matches: 14880
Saved: /content/hybrid_monthly/hybrid_2024_07.parquet

==================================================
Processing 2024-08
==================================================
SkyGuard rows: 14880
Hybrid rows: 14880
ERA5 matches: 14880
Saved: /content/hybrid_monthly/hybrid_2024_08.parquet

==================================================
Processing 2024-09
==================================================
SkyGuard rows: 14400
Hybrid rows: 14400
ERA5 matches: 14400
Saved: /content/hybrid_monthly/hybrid_2024_09.parquet

==================================================
Processing 2024-10
==================================================
SkyGuard rows: 14880
Hybrid rows: 14880
ERA5 matches: 14880
Saved: /content/hybrid_monthly/hybrid_2024_10.parquet

==================================================
Processing 2024-11
==================================================
SkyGuard rows: 14400
Hybrid rows: 14400
ERA5 matches: 14400
Saved: /content/hybrid_monthly/hybrid_2024_11.parquet

==================================================
Processing 2024-12
==================================================
SkyGuard rows: 14880
Hybrid rows: 14880
ERA5 matches: 14880
Saved: /content/hybrid_monthly/hybrid_2024_12.parquet

==================================================
Processing 2025-01
==================================================
SkyGuard rows: 14880
Hybrid rows: 14880
ERA5 matches: 14880
Saved: /content/hybrid_monthly/hybrid_2025_01.parquet

==================================================
Processing 2025-02
==================================================
SkyGuard rows: 13440
Hybrid rows: 13440
ERA5 matches: 13440
Saved: /content/hybrid_monthly/hybrid_2025_02.parquet

==================================================
Processing 2025-03
==================================================
SkyGuard rows: 14880
Hybrid rows: 14880
ERA5 matches: 14880
Saved: /content/hybrid_monthly/hybrid_2025_03.parquet

==================================================
Processing 2025-04
==================================================
SkyGuard rows: 14400
Hybrid rows: 14400
ERA5 matches: 14400
Saved: /content/hybrid_monthly/hybrid_2025_04.parquet

==================================================
Processing 2025-05
==================================================
SkyGuard rows: 14880
Hybrid rows: 14880
ERA5 matches: 14880
Saved: /content/hybrid_monthly/hybrid_2025_05.parquet

==================================================
Processing 2025-06
==================================================
SkyGuard rows: 14400
Hybrid rows: 14400
ERA5 matches: 14400
Saved: /content/hybrid_monthly/hybrid_2025_06.parquet

==================================================
Processing 2025-07
==================================================
SkyGuard rows: 14880
Hybrid rows: 14880
ERA5 matches: 14880
Saved: /content/hybrid_monthly/hybrid_2025_07.parquet

==================================================
Processing 2025-08
==================================================
SkyGuard rows: 14880
Hybrid rows: 14880
ERA5 matches: 14880
Saved: /content/hybrid_monthly/hybrid_2025_08.parquet

==================================================
Processing 2025-09
==================================================
SkyGuard rows: 14400
Hybrid rows: 14400
ERA5 matches: 14400
Saved: /content/hybrid_monthly/hybrid_2025_09.parquet

==================================================
Processing 2025-10
==================================================
SkyGuard rows: 14880
Hybrid rows: 14880
ERA5 matches: 14880
Saved: /content/hybrid_monthly/hybrid_2025_10.parquet

==================================================
Processing 2025-11
==================================================
SkyGuard rows: 14400
Hybrid rows: 14400
ERA5 matches: 14400
Saved: /content/hybrid_monthly/hybrid_2025_11.parquet

==================================================
Processing 2025-12
==================================================
SkyGuard rows: 14880
Hybrid rows: 14880
ERA5 matches: 14880
Saved: /content/hybrid_monthly/hybrid_2025_12.parquet

==================================================
Processing 2026-01
==================================================
SkyGuard rows: 14880
Hybrid rows: 14880
ERA5 matches: 14880
Saved: /content/hybrid_monthly/hybrid_2026_01.parquet

==================================================
Processing 2026-02
==================================================
SkyGuard rows: 13440
Hybrid rows: 13440
ERA5 matches: 13440
Saved: /content/hybrid_monthly/hybrid_2026_02.parquet

==================================================
Processing 2026-03
==================================================
SkyGuard rows: 14880
Hybrid rows: 14880
ERA5 matches: 14880
Saved: /content/hybrid_monthly/hybrid_2026_03.parquet

==================================================
Processing 2026-04
==================================================
SkyGuard rows: 14400
Hybrid rows: 14400
ERA5 matches: 14400
Saved: /content/hybrid_monthly/hybrid_2026_04.parquet

==================================================
Processing 2026-05
==================================================
SkyGuard rows: 14880
Hybrid rows: 14880
ERA5 matches: 14880
Saved: /content/hybrid_monthly/hybrid_2026_05.parquet

==================================================
Processing 2026-06
==================================================
SkyGuard rows: 12000
Hybrid rows: 12000
ERA5 matches: 12000
Saved: /content/hybrid_monthly/hybrid_2026_06.parquet

==================================================
🎉 HYBRID PROCESSING FINISHED
==================================================

Successful: 30
Failed: 0

In [78]:
# ==========================================
# STEP 13B — VERIFY ALL HYBRID FILES
# ==========================================

hybrid_files = sorted(
    f for f in os.listdir(HYBRID_DIR)
    if f.endswith(".parquet")
)

print("Hybrid files:", len(hybrid_files))

for f in hybrid_files:
    print(f)

Hybrid files: 30
hybrid_2024_01.parquet
hybrid_2024_02.parquet
hybrid_2024_03.parquet
hybrid_2024_04.parquet
hybrid_2024_05.parquet
hybrid_2024_06.parquet
hybrid_2024_07.parquet
hybrid_2024_08.parquet
hybrid_2024_09.parquet
hybrid_2024_10.parquet
hybrid_2024_11.parquet
hybrid_2024_12.parquet
hybrid_2025_01.parquet
hybrid_2025_02.parquet
hybrid_2025_03.parquet
hybrid_2025_04.parquet
hybrid_2025_05.parquet
hybrid_2025_06.parquet
hybrid_2025_07.parquet
hybrid_2025_08.parquet
hybrid_2025_09.parquet
hybrid_2025_10.parquet
hybrid_2025_11.parquet
hybrid_2025_12.parquet
hybrid_2026_01.parquet
hybrid_2026_02.parquet
hybrid_2026_03.parquet
hybrid_2026_04.parquet
hybrid_2026_05.parquet
hybrid_2026_06.parquet

In [79]:
# ==========================================
# STEP 14 — COMBINE ALL HYBRID FILES
# ==========================================

import pandas as pd
import os
import gc

hybrid_files = sorted(
    os.path.join(HYBRID_DIR, f)
    for f in os.listdir(HYBRID_DIR)
    if f.endswith(".parquet")
)

print("Files to combine:", len(hybrid_files))

hybrid_final = pd.concat(
    [
        pd.read_parquet(f)
        for f in hybrid_files
    ],
    ignore_index=True
)

print("\n===================================")
print("FINAL HYBRID DATASET")
print("===================================")

print("Rows:", len(hybrid_final))
print("Columns:", len(hybrid_final.columns))

print("\nColumns:")
print(hybrid_final.columns.tolist())

Files to combine: 30

===================================
FINAL HYBRID DATASET
===================================
Rows: 435360
Columns: 29

Columns:
['timestamp', 'station_id', 'station_name', 'latitude', 'longitude', 'temperature_C_skyguard', 'pressure_hPa_skyguard', 'relative_humidity_pct_skyguard', 'anomaly', 'anomaly_type', 'severity', 'injected', 'temperature_valid', 'pressure_valid', 'humidity_valid', 'has_missing_weather', 'temperature_C_clean', 'pressure_hPa_clean', 'relative_humidity_pct_clean', 'era5_latitude', 'era5_longitude', 'valid_time', 'temperature_C_era5', 'pressure_hPa_era5', 'relative_humidity_pct_era5', 'temperature_difference', 'pressure_difference', 'humidity_difference', 'era5_match']

In [80]:
print("Start:")
print(hybrid_final["timestamp"].min())

print("\nEnd:")
print(hybrid_final["timestamp"].max())

print("\nUnique stations:")
print(hybrid_final["station_id"].nunique())

print("\nStations:")
print(
    sorted(
        hybrid_final["station_id"].unique()
    )
)

Start:
2024-01-01 00:00:00+00:00

End:
2026-06-25 23:00:00+00:00

Unique stations:
20

Stations:
['ST001', 'ST002', 'ST003', 'ST004', 'ST005', 'ST006', 'ST007', 'ST008', 'ST009', 'ST010', 'ST011', 'ST012', 'ST013', 'ST014', 'ST015', 'ST016', 'ST017', 'ST018', 'ST019', 'ST020']

In [81]:
print("ERA5 matching quality")
print("=====================")

print(
    hybrid_final["era5_match"]
    .value_counts(dropna=False)
)

match_rate = (
    hybrid_final["era5_match"].mean() * 100
)

print(
    f"\nERA5 match rate: {match_rate:.2f}%"
)

ERA5 matching quality
=====================
era5_match
True    435360
Name: count, dtype: int64

ERA5 match rate: 100.00%

In [82]:
duplicate_count = hybrid_final.duplicated(
    subset=["station_id", "timestamp"]
).sum()

print(
    "Duplicate station-timestamp rows:",
    duplicate_count
)

Duplicate station-timestamp rows: 155988

In [83]:
# ==========================================
# STEP 14H — INVESTIGATE DUPLICATES
# ==========================================

dup_mask = hybrid_final.duplicated(
    subset=["station_id", "timestamp"],
    keep=False
)

duplicates = hybrid_final[dup_mask].copy()

print("Total duplicate rows:", len(duplicates))

print(
    "Unique duplicated station-timestamp pairs:",
    duplicates[
        ["station_id", "timestamp"]
    ].drop_duplicates().shape[0]
)

print("\nSample duplicate records:")

display(
    duplicates[
        [
            "station_id",
            "timestamp",
            "temperature_C_skyguard",
            "pressure_hPa_skyguard",
            "relative_humidity_pct_skyguard",
            "anomaly",
            "anomaly_type",
            "severity",
            "injected"
        ]
    ]
    .sort_values(
        ["station_id", "timestamp"]
    )
    .head(20)
)

Total duplicate rows: 270892
Unique duplicated station-timestamp pairs: 114904

Sample duplicate records:

,station_id,timestamp,temperature_C_skyguard,pressure_hPa_skyguard,relative_humidity_pct_skyguard,anomaly,anomaly_type,severity,injected
43,ST001,2024-01-01 02:00:00+00:00,16.84,1005.33,71.32,0,normal,normal,False
48,ST001,2024-01-01 02:00:00+00:00,15.24,1002.21,68.59,0,normal,normal,False
181,ST001,2024-01-01 09:00:00+00:00,21.13,1001.01,75.66,0,normal,normal,False
188,ST001,2024-01-01 09:00:00+00:00,22.65,999.05,76.44,0,normal,normal,False
248,ST001,2024-01-01 12:00:00+00:00,23.94,1003.20,70.58,0,normal,normal,False
259,ST001,2024-01-01 12:00:00+00:00,23.75,1001.21,64.21,0,normal,normal,False
380,ST001,2024-01-01 19:00:00+00:00,20.27,1002.31,80.62,0,normal,normal,False
382,ST001,2024-01-01 19:00:00+00:00,16.02,1002.61,75.90,0,normal,normal,False
574,ST001,2024-01-02 04:00:00+00:00,18.64,1002.89,79.53,0,normal,normal,False
579,ST001,2024-01-02 04:00:00+00:00,16.36,1000.44,71.41,0,normal,normal,False
600,ST001,2024-01-02 06:00:00+00:00,17.18,1004.50,74.38,0,normal,normal,False
616,ST001,2024-01-02 06:00:00+00:00,20.96,1006.79,76.15,0,normal,normal,False
632,ST001,2024-01-02 07:00:00+00:00,19.86,1002.29,70.50,0,normal,normal,False
637,ST001,2024-01-02 07:00:00+00:00,19.74,1005.37,68.20,0,normal,normal,False
662,ST001,2024-01-02 09:00:00+00:00,20.31,1005.06,69.37,0,normal,normal,False
679,ST001,2024-01-02 09:00:00+00:00,21.44,1003.25,74.86,0,normal,normal,False
744,ST001,2024-01-02 13:00:00+00:00,21.82,1002.87,61.10,0,normal,normal,False
747,ST001,2024-01-02 13:00:00+00:00,22.33,1005.76,75.21,0,normal,normal,False
907,ST001,2024-01-02 21:00:00+00:00,18.14,1001.83,76.09,0,normal,normal,False
914,ST001,2024-01-02 21:00:00+00:00,16.78,1003.26,78.79,0,normal,normal,False

In [84]:
# How many records exist per station-timestamp?

duplicate_counts = (
    hybrid_final
    .groupby(
        ["station_id", "timestamp"]
    )
    .size()
    .value_counts()
    .sort_index()
)

print("Records per station-timestamp:")
print(duplicate_counts)

Records per station-timestamp:
1    164468
2     82015
3     25919
4      5890
5       950
6       116
7        13
8         1
Name: count, dtype: int64

In [85]:
# ==========================================
# STEP 15 — UNIQUE OBSERVATION ID
# ==========================================

hybrid_final = hybrid_final.reset_index(drop=True)

hybrid_final["observation_id"] = (
    hybrid_final.index
)

print("✅ Observation IDs created")

print(
    hybrid_final[
        [
            "observation_id",
            "station_id",
            "timestamp"
        ]
    ].head(10)
)

✅ Observation IDs created
   observation_id station_id                 timestamp
0               0      ST002 2024-01-01 00:00:00+00:00
1               1      ST006 2024-01-01 00:00:00+00:00
2               2      ST015 2024-01-01 00:00:00+00:00
3               3      ST011 2024-01-01 00:00:00+00:00
4               4      ST004 2024-01-01 00:00:00+00:00
5               5      ST005 2024-01-01 00:00:00+00:00
6               6      ST013 2024-01-01 00:00:00+00:00
7               7      ST020 2024-01-01 00:00:00+00:00
8               8      ST002 2024-01-01 00:00:00+00:00
9               9      ST008 2024-01-01 00:00:00+00:00

In [86]:
# ==========================================
# STEP 15 — UNIQUE OBSERVATION ID
# ==========================================

hybrid_final = hybrid_final.reset_index(drop=True)

hybrid_final["observation_id"] = (
    hybrid_final.index
)

print("✅ Observation IDs created")

print(
    hybrid_final[
        [
            "observation_id",
            "station_id",
            "timestamp"
        ]
    ].head(10)
)

✅ Observation IDs created
   observation_id station_id                 timestamp
0               0      ST002 2024-01-01 00:00:00+00:00
1               1      ST006 2024-01-01 00:00:00+00:00
2               2      ST015 2024-01-01 00:00:00+00:00
3               3      ST011 2024-01-01 00:00:00+00:00
4               4      ST004 2024-01-01 00:00:00+00:00
5               5      ST005 2024-01-01 00:00:00+00:00
6               6      ST013 2024-01-01 00:00:00+00:00
7               7      ST020 2024-01-01 00:00:00+00:00
8               8      ST002 2024-01-01 00:00:00+00:00
9               9      ST008 2024-01-01 00:00:00+00:00

In [87]:
# ==========================================
# DUPLICATE TIMESTAMPS VS ANOMALIES
# ==========================================

dup_groups = (
    hybrid_final
    .groupby(["station_id", "timestamp"])
    .agg(
        observation_count=("observation_id", "count"),
        anomaly_count=("anomaly", "sum"),
        injected_count=("injected", "sum")
    )
    .reset_index()
)

print("Duplicate groups containing anomalies:")

display(
    dup_groups[
        (dup_groups["observation_count"] > 1) &
        (dup_groups["anomaly_count"] > 0)
    ].head(20)
)

print(
    "\nNumber of duplicate groups containing anomalies:",
    (
        (dup_groups["observation_count"] > 1) &
        (dup_groups["anomaly_count"] > 0)
    ).sum()
)

Duplicate groups containing anomalies:

,station_id,timestamp,observation_count,anomaly_count,injected_count
31,ST001,2024-01-03 03:00:00+00:00,3,1,1
40,ST001,2024-01-03 17:00:00+00:00,2,1,1
56,ST001,2024-01-05 05:00:00+00:00,2,1,1
96,ST001,2024-01-07 08:00:00+00:00,3,1,1
97,ST001,2024-01-07 09:00:00+00:00,2,1,1
107,ST001,2024-01-08 00:00:00+00:00,2,1,1
115,ST001,2024-01-08 09:00:00+00:00,2,1,1
134,ST001,2024-01-09 13:00:00+00:00,2,1,1
142,ST001,2024-01-10 04:00:00+00:00,4,1,1
192,ST001,2024-01-13 14:00:00+00:00,2,1,1
210,ST001,2024-01-14 19:00:00+00:00,4,1,1
220,ST001,2024-01-15 12:00:00+00:00,3,1,1
221,ST001,2024-01-15 13:00:00+00:00,2,1,1
230,ST001,2024-01-16 03:00:00+00:00,2,1,1
264,ST001,2024-01-18 06:00:00+00:00,3,1,1
274,ST001,2024-01-18 20:00:00+00:00,4,1,1
320,ST001,2024-01-21 15:00:00+00:00,3,1,1
323,ST001,2024-01-21 20:00:00+00:00,2,1,1
334,ST001,2024-01-22 14:00:00+00:00,4,1,1
340,ST001,2024-01-22 20:00:00+00:00,2,1,1

Number of duplicate groups containing anomalies: 20416

In [88]:
# ==========================================
# STEP 16 — CHRONOLOGICAL TRAIN/TEST SPLIT
# ==========================================

train_df = hybrid_final[
    (hybrid_final["timestamp"] >= "2024-01-01 00:00:00+00:00") &
    (hybrid_final["timestamp"] <  "2025-01-01 00:00:00+00:00")
].copy()

test_df = hybrid_final[
    (hybrid_final["timestamp"] >= "2025-01-01 00:00:00+00:00") &
    (hybrid_final["timestamp"] <  "2026-01-01 00:00:00+00:00")
].copy()

final_test_df = hybrid_final[
    hybrid_final["timestamp"] >= "2026-01-01 00:00:00+00:00"
].copy()

print("===================================")
print("DATASET SPLIT")
print("===================================")

print("\nTRAIN — 2024")
print("Rows:", len(train_df))
print(
    "Period:",
    train_df["timestamp"].min(),
    "→",
    train_df["timestamp"].max()
)

print("\nTEST — 2025")
print("Rows:", len(test_df))
print(
    "Period:",
    test_df["timestamp"].min(),
    "→",
    test_df["timestamp"].max()
)

print("\nFINAL TEST — 2026")
print("Rows:", len(final_test_df))
print(
    "Period:",
    final_test_df["timestamp"].min(),
    "→",
    final_test_df["timestamp"].max()
)

===================================
DATASET SPLIT
===================================

TRAIN — 2024
Rows: 175680
Period: 2024-01-01 00:00:00+00:00 → 2024-12-31 23:00:00+00:00

TEST — 2025
Rows: 175200
Period: 2025-01-01 00:00:00+00:00 → 2025-12-31 23:00:00+00:00

FINAL TEST — 2026
Rows: 84480
Period: 2026-01-01 00:00:00+00:00 → 2026-06-25 23:00:00+00:00

In [89]:
# ==========================================
# STEP 16 — CHRONOLOGICAL TRAIN/TEST SPLIT
# ==========================================

train_df = hybrid_final[
    (hybrid_final["timestamp"] >= "2024-01-01 00:00:00+00:00") &
    (hybrid_final["timestamp"] <  "2025-01-01 00:00:00+00:00")
].copy()

test_df = hybrid_final[
    (hybrid_final["timestamp"] >= "2025-01-01 00:00:00+00:00") &
    (hybrid_final["timestamp"] <  "2026-01-01 00:00:00+00:00")
].copy()

final_test_df = hybrid_final[
    hybrid_final["timestamp"] >= "2026-01-01 00:00:00+00:00"
].copy()

print("===================================")
print("DATASET SPLIT")
print("===================================")

print("\nTRAIN — 2024")
print("Rows:", len(train_df))
print(
    "Period:",
    train_df["timestamp"].min(),
    "→",
    train_df["timestamp"].max()
)

print("\nTEST — 2025")
print("Rows:", len(test_df))
print(
    "Period:",
    test_df["timestamp"].min(),
    "→",
    test_df["timestamp"].max()
)

print("\nFINAL TEST — 2026")
print("Rows:", len(final_test_df))
print(
    "Period:",
    final_test_df["timestamp"].min(),
    "→",
    final_test_df["timestamp"].max()
)

===================================
DATASET SPLIT
===================================

TRAIN — 2024
Rows: 175680
Period: 2024-01-01 00:00:00+00:00 → 2024-12-31 23:00:00+00:00

TEST — 2025
Rows: 175200
Period: 2025-01-01 00:00:00+00:00 → 2025-12-31 23:00:00+00:00

FINAL TEST — 2026
Rows: 84480
Period: 2026-01-01 00:00:00+00:00 → 2026-06-25 23:00:00+00:00

In [90]:
# ==========================================
# STEP 18 — SAVE TRAIN / TEST DATASETS
# ==========================================

train_path = "/content/skyguard_train_2024.parquet"
test_path = "/content/skyguard_test_2025.parquet"
final_test_path = "/content/skyguard_final_test_2026.parquet"

train_df.to_parquet(
    train_path,
    index=False
)

test_df.to_parquet(
    test_path,
    index=False
)

final_test_df.to_parquet(
    final_test_path,
    index=False
)

print("✅ DATASETS SAVED")

print("\nTrain:")
print(train_path)

print("\nTest:")
print(test_path)

print("\nFinal test:")
print(final_test_path)

✅ DATASETS SAVED

Train:
/content/skyguard_train_2024.parquet

Test:
/content/skyguard_test_2025.parquet

Final test:
/content/skyguard_final_test_2026.parquet

In [91]:
# ==========================================
# STEP 19 — DATA ENGINEERING SUMMARY
# ==========================================

print("\n" + "="*60)
print("        SKYGUARD HYBRID DATA ENGINEERING REPORT")
print("="*60)

print("\nSOURCE DATA")
print("-"*60)

print("SkyGuard observations:", len(skyguard_df))
print("Stations:", skyguard_df["station_id"].nunique())

print("\nERA5 DATA")
print("-"*60)

print("Processed monthly files:", len(hybrid_files))
print("Coverage: January 2024 → June 2026")

print("\nHYBRID DATA")
print("-"*60)

print("Total observations:", len(hybrid_final))
print("Stations:", hybrid_final["station_id"].nunique())

print(
    "ERA5 match rate:",
    f"{hybrid_final['era5_match'].mean()*100:.2f}%"
)

print(
    "Unique observations:",
    hybrid_final["observation_id"].nunique()
)

print("\nDATASET SPLIT")
print("-"*60)

print("Train 2024:", len(train_df))
print("Test 2025:", len(test_df))
print("Final Test 2026:", len(final_test_df))

print("\nQUALITY")
print("-"*60)

print(
    "Duplicate station-timestamp groups:",
    (dup_groups["observation_count"] > 1).sum()
)

print(
    "Duplicate groups containing anomalies:",
    (
        (dup_groups["observation_count"] > 1) &
        (dup_groups["anomaly_count"] > 0)
    ).sum()
)

print("\n" + "="*60)
print("                DATA ENGINEERING COMPLETE")
print("="*60)

============================================================
        SKYGUARD HYBRID DATA ENGINEERING REPORT
============================================================

SOURCE DATA
------------------------------------------------------------
SkyGuard observations: 1000000
Stations: 20

ERA5 DATA
------------------------------------------------------------
Processed monthly files: 30
Coverage: January 2024 → June 2026

HYBRID DATA
------------------------------------------------------------
Total observations: 435360
Stations: 20
ERA5 match rate: 100.00%
Unique observations: 435360

DATASET SPLIT
------------------------------------------------------------
Train 2024: 175680
Test 2025: 175200
Final Test 2026: 84480

QUALITY
------------------------------------------------------------
Duplicate station-timestamp groups: 114904
Duplicate groups containing anomalies: 20416

============================================================
                DATA ENGINEERING COMPLETE
============================================================

In [92]:
# Check EXACT duplicate rows

exact_duplicates = hybrid_final.duplicated(keep=False)

print("Exact duplicate rows:", exact_duplicates.sum())

if exact_duplicates.sum() > 0:
    print("\nSample exact duplicates:")
    display(
        hybrid_final[exact_duplicates].head(10)
    )

Exact duplicate rows: 0

In [93]:
import os

files = [
    "/content/skyguard_train_2024.parquet",
    "/content/skyguard_test_2025.parquet",
    "/content/skyguard_final_test_2026.parquet"
]

for f in files:
    print(f, "→", os.path.exists(f))

/content/skyguard_train_2024.parquet → True
/content/skyguard_test_2025.parquet → True
/content/skyguard_final_test_2026.parquet → True

In [94]:
from google.colab import files

files.download("/content/skyguard_train_2024.parquet")

In [95]:
files.download("/content/skyguard_test_2025.parquet")

In [96]:
files.download("/content/skyguard_final_test_2026.parquet")

In [97]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [99]:
import os

os.makedirs(
    "/content/drive/MyDrive/SKYGUARD_DATA",
    exist_ok=True
)

In [100]:
import shutil

files_to_backup = [
    "skyguard_train_2024.parquet",
    "skyguard_test_2025.parquet",
    "skyguard_final_test_2026.parquet"
]

for filename in files_to_backup:
    shutil.copy(
        f"/content/{filename}",
        f"/content/drive/MyDrive/SKYGUARD_DATA/{filename}"
    )

print("✅ All three files backed up to Google Drive!")

✅ All three files backed up to Google Drive!

In [101]:
train_df.to_csv(
    "/content/skyguard_train_2024.csv",
    index=False
)

test_df.to_csv(
    "/content/skyguard_test_2025.csv",
    index=False
)

final_test_df.to_csv(
    "/content/skyguard_final_test_2026.csv",
    index=False
)

print("✅ CSV files created!")

✅ CSV files created!

In [102]:
import os

for f in [
    "skyguard_train_2024.csv",
    "skyguard_test_2025.csv",
    "skyguard_final_test_2026.csv"
]:
    path = "/content/" + f
    print(f, "→", os.path.getsize(path) / (1024**2), "MB")

skyguard_train_2024.csv → 45.016075134277344 MB
skyguard_test_2025.csv → 44.98651123046875 MB
skyguard_final_test_2026.csv → 21.685437202453613 MB

In [103]:
from google.colab import files

files.download("/content/skyguard_train_2024.csv")

In [104]:
files.download("/content/skyguard_test_2025.csv")

In [105]:
files.download("/content/skyguard_final_test_2026.csv")